<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">buildEmailExtField</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required to</value>
    <value>[i] field:0:required cc</value>
    <value>[i] field:0:required bcc</value>
    <value>[i] field:0:required subject</value>
    <value>[i] field:0:required subjectCharset</value>
    <value>[i] field:0:required charset</value>
    <value>[i] field:0:required from</value>
    <value>[i] field:0:required mailhost</value>
    <value>[i] field:0:required body</value>
    <value>[i] field:0:required attachcontenttype</value>
    <value>[i] field:0:required attachencoding</value>
    <value>[i] field:0:required attachcharset</value>
    <value>[o] field:0:required string</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9kZWZpbmUgaW5wdXQgdmFyaWFibGVzDQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IG51bGw7
DQoNCg0KdHJ5ew0KCWlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoJU3RyaW5n
IGVtYWlsZXh0ZmllbGQgPSBuZXcgU3RyaW5nKCk7DQoJDQpTdHJpbmcgdG1wID0gbmV3IFN0cmlu
ZygpOw0KDQoJaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJ0byIpKSANCgl7DQoJCXRtcCA9IChTdHJp
bmcpaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsNCgl9DQoNCgl0bXAgPSB0bXAudHJpbSgpOw0KCWVt
YWlsZXh0ZmllbGQgPSBlbWFpbGV4dGZpZWxkICsgIjx0bz4iOw0KCWVtYWlsZXh0ZmllbGQgPSBl
bWFpbGV4dGZpZWxkICsgdG1wOw0KCWVtYWlsZXh0ZmllbGQgPSBlbWFpbGV4dGZpZWxkICsgIjwv
dG8+XG4iOw0KCXRtcCA9ICIiOw0KDQoJaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJjYyIpKQ0KCXsN
CgkJdG1wID0gKFN0cmluZylpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOw0KCX0NCg0KCXRtcCA9IHRt
cC50cmltKCk7DQoJZW1haWxleHRmaWVsZCA9IGVtYWlsZXh0ZmllbGQgKyAiPGNjPiI7DQoJZW1h
aWxleHRmaWVsZCA9IGVtYWlsZXh0ZmllbGQgKyB0bXA7DQoJZW1haWxleHRmaWVsZCA9IGVtYWls
ZXh0ZmllbGQgKyAiPC9jYz5cbiI7DQoJdG1wID0gIiI7DQoNCglpZiAoaWRjUGlwZWxpbmUuZmly
c3QoImJjYyIpKSANCgl7DQoJCXRtcCA9IChTdHJpbmcpaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsN
Cgl9DQoNCgl0bXAgPSB0bXAudHJpbSgpOw0KCWVtYWlsZXh0ZmllbGQgPSBlbWFpbGV4dGZpZWxk
ICsgIjxiY2M+IjsNCgllbWFpbGV4dGZpZWxkID0gZW1haWxleHRmaWVsZCArIHRtcDsNCgllbWFp
bGV4dGZpZWxkID0gZW1haWxleHRmaWVsZCArICI8L2JjYz5cbiI7DQoJdG1wID0gIiI7DQoNCglp
ZiAoaWRjUGlwZWxpbmUuZmlyc3QoInN1YmplY3QiKSkgDQoJew0KCQl0bXAgPSAoU3RyaW5nKWlk
Y1BpcGVsaW5lLmdldFZhbHVlKCk7DQoJfQ0KDQoJdG1wID0gdG1wLnRyaW0oKTsNCgllbWFpbGV4
dGZpZWxkID0gZW1haWxleHRmaWVsZCArICI8c3ViamVjdD4iOw0KCWVtYWlsZXh0ZmllbGQgPSBl
bWFpbGV4dGZpZWxkICsgdG1wOw0KCWVtYWlsZXh0ZmllbGQgPSBlbWFpbGV4dGZpZWxkICsgIjwv
c3ViamVjdD5cbiI7DQoJdG1wID0gIiI7DQoNCglpZiAoaWRjUGlwZWxpbmUuZmlyc3QoInN1Ympl
Y3RDaGFyc2V0IikpIA0KCXsNCgkJdG1wID0gKFN0cmluZylpZGNQaXBlbGluZS5nZXRWYWx1ZSgp
Ow0KCX0NCg0KCXRtcCA9IHRtcC50cmltKCk7DQoJZW1haWxleHRmaWVsZCA9IGVtYWlsZXh0Zmll
bGQgKyAiPHN1YmplY3RDaGFyc2V0PiI7DQoJZW1haWxleHRmaWVsZCA9IGVtYWlsZXh0ZmllbGQg
KyB0bXA7DQoJZW1haWxleHRmaWVsZCA9IGVtYWlsZXh0ZmllbGQgKyAiPC9zdWJqZWN0Q2hhcnNl
dD5cbiI7DQoJdG1wID0gIiI7DQoNCglpZiAoaWRjUGlwZWxpbmUuZmlyc3QoImNoYXJzZXQiKSkg
DQoJew0KCQl0bXAgPSAoU3RyaW5nKWlkY1BpcGVsaW5lLmdldFZhbHVlKCk7DQoJfQ0KDQoJdG1w
ID0gdG1wLnRyaW0oKTsNCgllbWFpbGV4dGZpZWxkID0gZW1haWxleHRmaWVsZCArICI8Y2hhcnNl
dD4iOw0KCWVtYWlsZXh0ZmllbGQgPSBlbWFpbGV4dGZpZWxkICsgdG1wOw0KCWVtYWlsZXh0Zmll
bGQgPSBlbWFpbGV4dGZpZWxkICsgIjwvY2hhcnNldD5cbiI7DQoJdG1wID0gIiI7DQoNCglpZiAo
aWRjUGlwZWxpbmUuZmlyc3QoImZyb20iKSkgDQoJew0KCQl0bXAgPSAoU3RyaW5nKWlkY1BpcGVs
aW5lLmdldFZhbHVlKCk7DQoJfQ0KDQoJdG1wID0gdG1wLnRyaW0oKTsNCgllbWFpbGV4dGZpZWxk
ID0gZW1haWxleHRmaWVsZCArICI8ZnJvbT4iOw0KCWVtYWlsZXh0ZmllbGQgPSBlbWFpbGV4dGZp
ZWxkICsgdG1wOw0KCWVtYWlsZXh0ZmllbGQgPSBlbWFpbGV4dGZpZWxkICsgIjwvZnJvbT5cbiI7
DQoJdG1wID0gIiI7DQoNCglpZiAoaWRjUGlwZWxpbmUuZmlyc3QoIm1haWxob3N0IikpIA0KCXsN
CgkJdG1wID0gKFN0cmluZylpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOw0KCX0NCg0KCXRtcCA9IHRt
cC50cmltKCk7DQoJZW1haWxleHRmaWVsZCA9IGVtYWlsZXh0ZmllbGQgKyAiPG1haWxob3N0PiI7
DQoJZW1haWxleHRmaWVsZCA9IGVtYWlsZXh0ZmllbGQgKyB0bXA7DQoJZW1haWxleHRmaWVsZCA9
IGVtYWlsZXh0ZmllbGQgKyAiPC9tYWlsaG9zdD5cbiI7DQoJdG1wID0gIiI7DQoNCglpZiAoaWRj
UGlwZWxpbmUuZmlyc3QoImJvZHkiKSkgDQoJew0KCQl0bXAgPSAoU3RyaW5nKWlkY1BpcGVsaW5l
LmdldFZhbHVlKCk7DQoJfQ0KDQoJdG1wID0gdG1wLnRyaW0oKTsNCgllbWFpbGV4dGZpZWxkID0g
ZW1haWxleHRmaWVsZCArICI8Ym9keT4iOw0KCWVtYWlsZXh0ZmllbGQgPSBlbWFpbGV4dGZpZWxk
ICsgdG1wOw0KCWVtYWlsZXh0ZmllbGQgPSBlbWFpbGV4dGZpZWxkICsgIjwvYm9keT5cbiI7DQoJ
dG1wID0gIiI7DQoNCglpZiAoaWRjUGlwZWxpbmUuZmlyc3QoImF0dGFjaGNvbnRlbnR0eXBlIikp
IA0KCXsNCgkJdG1wID0gKFN0cmluZylpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOw0KCX0NCg0KCXRt
cCA9IHRtcC50cmltKCk7DQoJZW1haWxleHRmaWVsZCA9IGVtYWlsZXh0ZmllbGQgKyAiPGF0dGFj
aGNvbnRlbnR0eXBlPiI7DQoJZW1haWxleHRmaWVsZCA9IGVtYWlsZXh0ZmllbGQgKyB0bXA7DQoJ
ZW1haWxleHRmaWVsZCA9IGVtYWlsZXh0ZmllbGQgKyAiPC9hdHRhY2hjb250ZW50dHlwZT5cbiI7
DQoJdG1wID0gIiI7DQoNCglpZiAoaWRjUGlwZWxpbmUuZmlyc3QoImF0dGFjaGVuY29kaW5nIikp
IA0KCXsNCgkJdG1wID0gKFN0cmluZylpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOw0KCX0NCg0KCXRt
cCA9IHRtcC50cmltKCk7DQoJZW1haWxleHRmaWVsZCA9IGVtYWlsZXh0ZmllbGQgKyAiPGF0dGFj
aGVuY29kaW5nPiI7DQoJZW1haWxleHRmaWVsZCA9IGVtYWlsZXh0ZmllbGQgKyB0bXA7DQoJZW1h
aWxleHRmaWVsZCA9IGVtYWlsZXh0ZmllbGQgKyAiPC9hdHRhY2hlbmNvZGluZz5cbiI7DQoJdG1w
ID0gIiI7DQoNCglpZiAoaWRjUGlwZWxpbmUuZmlyc3QoImF0dGFjaGNoYXJzZXQiKSkgDQoJew0K
CQl0bXAgPSAoU3RyaW5nKWlkY1BpcGVsaW5lLmdldFZhbHVlKCk7DQoJfQ0KDQoJdG1wID0gdG1w
LnRyaW0oKTsNCgllbWFpbGV4dGZpZWxkID0gZW1haWxleHRmaWVsZCArICI8YXR0YWNoY2hhcnNl
dD4iOw0KCWVtYWlsZXh0ZmllbGQgPSBlbWFpbGV4dGZpZWxkICsgdG1wOw0KCWVtYWlsZXh0Zmll
bGQgPSBlbWFpbGV4dGZpZWxkICsgIjwvYXR0YWNoY2hhcnNldD4iOw0KCWlkY1BpcGVsaW5lLmlu
c2VydEFmdGVyKCJzdHJpbmciLCBlbWFpbGV4dGZpZWxkKTsNCg0KfS8vIGVuZCBvZiB0cnkgYmxv
Y2sNCg0KY2F0Y2ggKEV4Y2VwdGlvbiBlKQ0Kew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9u
KGUuZ2V0TWVzc2FnZSgpKTsNCn0NCg0KDQpmaW5hbGx5IHsNCgkvL0Fsd2F5cyBkZXN0cm95IGN1
cnNvcnMgdGhhdCB5b3UgY3JlYXRlZA0KCWlmKGlkY1BpcGVsaW5lICE9IG51bGwgKSANCgkJaWRj
UGlwZWxpbmUuZGVzdHJveSgpOw0KfQ0K</value>
</Values>
