<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">openFileWriter</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[i] field:0:required overwriteFlag {"overwrite","append"}</value>
    <value>[o] object:0:required fileWriter</value>
    <value>[o] field:0:required successFlag</value>
    <value>[o] field:0:required error</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CQ0KSURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBudWxsOw0KLy9PdXRwdXQgVmFyaWFibGVzIA0K
U3RyaW5nIHN1Y2Nlc3NGbGFnID0gImZhbHNlIjsNClN0cmluZyBlcnJvck1zZyA9IG51bGw7DQpC
dWZmZXJlZFdyaXRlciBmaWxlV3JpdGVyID0gbnVsbDsNCnRyeQ0Kew0KCVN0cmluZyBzdHJGaWxl
bmFtZSA9IG51bGw7DQoJU3RyaW5nIHN0ck92ZXJ3cml0ZUZsYWcgPSBudWxsOw0KDQoJaWRjUGlw
ZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCg0KCS8vIENoZWNrIHRvIHNlZSBpZiB0aGUg
ZmlsZW5hbWUgb2JqZWN0IGlzIGluIHRoZSBwaXBlbGluZQ0KCWlmIChpZGNQaXBlbGluZS5maXJz
dCgiZmlsZW5hbWUiKSkNCgl7DQoJCS8vZ2V0IHRoZSBmaWxlbmFtZSBvdXQgb2YgdGhlIHBpcGVs
aW5lCQkJCQkJDQoJCXN0ckZpbGVuYW1lID0gKFN0cmluZylpZGNQaXBlbGluZS5nZXRWYWx1ZSgp
OwkNCg0KCX0NCgkvL2lmIGl0IGlzIG5vdCBpbiB0aGUgcGlwZWxpbmUsIHRoZW4gaGFuZGxlIHRo
ZSBlcnJvcg0KCWVsc2UNCgl7DQoJCXN1Y2Nlc3NGbGFnPSJmYWxzZSI7DQoJCWVycm9yTXNnID0g
ImZpbGVOYW1lIGNhbm5vdCBiZSBudWxsIjsNCg0KCQkvL2luc2VydCB0aGUgc3VjY2Vzc0ZsYWcg
aW50byB0aGUgcGlwZWxpbmUNCgkJLy9pZGNQaXBlbGluZS5pbnNlcnRBZnRlcigic3VjY2Vzc0Zs
YWciLCBzdWNjZXNzRmxhZyk7CQ0KCQkvL2lkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJlcnJvciIs
IGVycm9yTXNnKTsNCg0KCQlyZXR1cm47DQoJfQ0KDQoNCgkvLyBDaGVjayB0byBzZWUgaWYgdGhl
IG92ZXJ3cml0ZUZsYWcgb2JqZWN0IGlzIGluIHRoZSBwaXBlbGluZQ0KCWlmIChpZGNQaXBlbGlu
ZS5maXJzdCgib3ZlcndyaXRlRmxhZyIpKQkNCgl7DQoJCS8vZ2V0IHRoZSBvdmVyd3JpdGVGbGFn
IG91dCBvZiB0aGUgcGlwZWxpbmUJCQkJCQkNCgkJc3RyT3ZlcndyaXRlRmxhZyA9IChTdHJpbmcp
aWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsJIA0KCX0NCgkvL2lmIGl0IGlzIG5vdCBpbiB0aGUgcGlw
ZWxpbmUsIHRoZW4gaGFuZGxlIHRoZSBlcnJvcg0KCWVsc2UNCgl7DQoNCgkJc3VjY2Vzc0ZsYWc9
ImZhbHNlIjsNCgkJZXJyb3JNc2cgPSAib3ZlcndyaXRlIEZsYWcgbm90IGZvdW5kIjsNCg0KCQkv
L2luc2VydCB0aGUgc3VjY2Vzc0ZsYWcgaW50byB0aGUgcGlwZWxpbmUNCgkJLy9pZGNQaXBlbGlu
ZS5pbnNlcnRBZnRlcigic3VjY2Vzc0ZsYWciLCBzdWNjZXNzRmxhZyk7CQ0KCQkvL2lkY1BpcGVs
aW5lLmluc2VydEFmdGVyKCJlcnJvciIsIGVycm9yTXNnKTsNCgkNCgkJcmV0dXJuOw0KCX0NCg0K
DQoJLy8gQ2hlY2sgdG8gc2VlIGlmIHRoZSBvdmVyd3JpdGVGbGFnIHdhcyBzZXQgdG8gb3Zlcndy
aXRlDQoJaWYgKHN0ck92ZXJ3cml0ZUZsYWcuZXF1YWxzKCJvdmVyd3JpdGUiKSkgCQkJDQoJew0K
CQkvL0NyZWF0ZSBhIG5ldyBCdWZmZXJlZFdyaXRlciBvYmplY3QgdGhhdCB3aWxsIG92ZXJ3cml0
ZSB0aGUgb2xkIGZpbGUNCgkJZmlsZVdyaXRlciA9IG5ldyBCdWZmZXJlZFdyaXRlcihuZXcgRmls
ZVdyaXRlcihzdHJGaWxlbmFtZSwgZmFsc2UpKTsNCgl9DQoJLy8gQ2hlY2sgdG8gc2VlIGlmIHRo
ZSBvdmVyd3JpdGVGbGFnIHdhcyBzZXQgdG8gYXBwZW5kDQoJZWxzZQ0KCXsNCgkJLy9DcmVhdGUg
YSBuZXcgQnVmZmVyZWRXcml0ZXIgb2JqZWN0IHRoYXQgd2lsbCBhcHBlbmQgdG8gdGhlIG9sZCBm
aWxlDQoJCWZpbGVXcml0ZXIgPSBuZXcgQnVmZmVyZWRXcml0ZXIobmV3IEZpbGVXcml0ZXIoc3Ry
RmlsZW5hbWUsIHRydWUpKTsNCgl9DQoNCgkvL1NldCB0aGUgc3VjY2VzcyBmbGFnIGJlY2F1c2Ug
dGhlIHNlcnZpY2Ugd2FzIHN1Y2Nlc3NmdWwNCglzdWNjZXNzRmxhZyA9ICJ0cnVlIjsNCg0KCQ0K
DQp9Ly9lbmQgdHJ5DQoNCmNhdGNoIChqYXZhLmxhbmcuRXhjZXB0aW9uIGUpDQp7DQoJLy9TZXQg
dGhlIHN1Y2Nlc3MgZmxhZyBiZWNhdXNlIHRoZSBzZXJ2aWNlIGZhaWxlZA0KCXN1Y2Nlc3NGbGFn
ID0gImZhbHNlIjsNCgllcnJvck1zZyA9IGUuZ2V0TWVzc2FnZSgpOw0KDQoJdGhyb3cgbmV3IFNl
cnZpY2VFeGNlcHRpb24oZS5nZXRNZXNzYWdlKCkpOw0KfQ0KDQoNCmZpbmFsbHkgew0KDQoJLy9p
bnNlcnQgdGhlIGZpbGVXcml0ZXIgaW50byB0aGUgcGlwZWxpbmUNCglpZGNQaXBlbGluZS5pbnNl
cnRBZnRlcigiZmlsZVdyaXRlciIsIGZpbGVXcml0ZXIpOwkNCg0KCS8vaW5zZXJ0IHRoZSBzdWNj
ZXNzRmxhZyBpbnRvIHRoZSBwaXBlbGluZQ0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNj
ZXNzRmxhZyIsIHN1Y2Nlc3NGbGFnKTsJDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoImVycm9y
IiwgZXJyb3JNc2cpOw0KDQoNCgkvL0Fsd2F5cyBkZXN0cm95IGN1cnNvcnMgdGhhdCB5b3UgY3Jl
YXRlZA0KCWlkY1BpcGVsaW5lLmRlc3Ryb3koKTsNCn0JDQoJDQo=</value>
</Values>
