<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">flushFileWriter</value>
  <array name="sig" type="value" depth="1">
    <value>[i] object:0:required fileWriter</value>
    <value>[o] field:0:required successFlag</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9kZWZpbmUgaW5wdXQgdmFyaWFibGVzIA0KQnVmZmVyZWRXcml0ZXIgZmlsZVdyaXRlciA9IG51
bGw7DQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IG51bGw7DQovL091dHB1dCBWYXJpYWJsZXMg
DQpTdHJpbmcgc3VjY2Vzc0ZsYWcgPSAiZmFsc2UiOw0KdHJ5DQp7CQkJDQoJaWRjUGlwZWxpbmUg
PSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCg0KCS8vIENoZWNrIHRvIHNlZSBpZiB0aGUgZmlsZVdy
aXRlciBvYmplY3QgaXMgaW4gdGhlIHBpcGVsaW5lDQoJaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJm
aWxlV3JpdGVyIikpDQoJewkNCgkJLy9nZXQgdGhlIEJ1ZmZlcmVkV3JpdGVyIHN0cmVhbSBvdXQg
b2YgdGhlIHBpcGVsaW5lCQkJCQkNCgkJZmlsZVdyaXRlciA9IChCdWZmZXJlZFdyaXRlcikgaWRj
UGlwZWxpbmUuZ2V0VmFsdWUoKTsNCgl9DQoJLy9pZiBpdCBpcyBub3QgaW4gdGhlIHBpcGVsaW5l
LCB0aGVuIGhhbmRsZSB0aGUgZXJyb3INCgllbHNlDQoJew0KCQlzdWNjZXNzRmxhZyA9ICJmYWxz
ZSI7CQ0KCQlyZXR1cm47DQoJfQ0KDQoJZmlsZVdyaXRlci5mbHVzaCgpOw0KCXN1Y2Nlc3NGbGFn
ID0gInRydWUiOwkJCQkJCQ0KCS8vaW5zZXJ0IHRoZSBzdWNjZXNzRmxhZyBpbnRvIHRoZSBwaXBl
bGluZQ0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIsIHN1Y2Nlc3NGbGFn
KTsNCn0vL2VuZCBvZiB0cnkNCmNhdGNoIChqYXZhLmxhbmcuRXhjZXB0aW9uIGUpDQp7DQoNCgkv
L1NldCB0aGUgc3VjY2VzcyBmbGFnIGJlY2F1c2UgdGhlIHNlcnZpY2UgZmFpbGVkDQoJc3VjY2Vz
c0ZsYWcgPSAiZmFsc2UiOw0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIs
IHN1Y2Nlc3NGbGFnKTsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlLmdldE1lc3NhZ2Uo
KSk7DQp9IGZpbmFsbHkgew0KDQoJLy9yZW1vdmUgYW55IG90aGVyIHN1Y2Nlc3NGbGFncyBmcm9t
IHBpcGxpbmUNCglpZihpZGNQaXBlbGluZS5maXJzdCgic3VjY2Vzc0ZsYWciKSkNCgl7DQoJCWlk
Y1BpcGVsaW5lLmRlbGV0ZSgpOw0KCX0NCg0KCS8vQWx3YXlzIGRlc3Ryb3kgY3Vyc29ycyB0aGF0
IHlvdSBjcmVhdGVkDQoJaWYoaWRjUGlwZWxpbmUgIT0gbnVsbCApIA0KCQlpZGNQaXBlbGluZS5k
ZXN0cm95KCk7DQp9CQ0KCQ0K</value>
</Values>
