<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parseHTTPURL</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required string</value>
    <value>[o] field:0:required authtype</value>
    <value>[o] field:0:required authusername</value>
    <value>[o] field:0:required authpassword</value>
    <value>[o] field:0:required encodingtype</value>
    <value>[o] field:0:required httpurl</value>
    <value>[o] field:0:required error</value>
    <value>[o] field:0:required successFlag</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBudWxsDQo7DQoNCnRyeXsNClN0cmluZyBodHRwc3Ry
aW5nOw0KaW50IGJpbmRleDsNCmludCBlaW5kZXg7DQoNCmlkY1BpcGVsaW5lID0gcGlwZWxpbmUu
Z2V0Q3Vyc29yKCk7DQoNClN0cmluZyBzdWNjZXNzRmxhZyA9ICJmYWxzZSI7DQoNCmlmIChpZGNQ
aXBlbGluZS5maXJzdCgic3RyaW5nIikpIHsNCglodHRwc3RyaW5nID0gKFN0cmluZylpZGNQaXBl
bGluZS5nZXRWYWx1ZSgpOw0KfQ0KZWxzZSB7DQoNCg0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVy
KCJzdWNjZXNzRmxhZyIsIHN1Y2Nlc3NGbGFnKTsNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigi
ZXJyb3IiLCAiTm8gaW5wdXQgc3RyaW5nIGZvciBodHRwIHVybC4iKTsNCg0KCXJldHVybjsNCn0N
Cg0KaHR0cHN0cmluZyA9IGh0dHBzdHJpbmcudHJpbSgpOw0KDQpiaW5kZXggPSBodHRwc3RyaW5n
LmluZGV4T2YoIjxhdXRodHlwZT4iLCAwKTsNCg0KaWYoYmluZGV4IDwgMCkgew0KDQoJaWRjUGlw
ZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVs
aW5lLmluc2VydEFmdGVyKCJlcnJvciIsICJUaGUgPGF1dGh0eXBlPiB0YWcgaXMgbWlzc2luZyBm
cm9tIHRoZSBodHRwIHByb2ZpbGUuIik7DQoJcmV0dXJuOw0KDQp9DQoNCmVpbmRleCA9IGh0dHBz
dHJpbmcuaW5kZXhPZigiPC9hdXRodHlwZT4iLCAwKTsNCg0KaWYoZWluZGV4IDwgMCkgew0KDQoJ
aWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlk
Y1BpcGVsaW5lLmluc2VydEFmdGVyKCJlcnJvciIsICJUaGUgPC9hdXRodHlwZT4gdGFnIGlzIG1p
c3NpbmcgZnJvbSBiZWdpbmluZyBvZiB0aGUgaHR0cCBwcm9maWxlLiIpOw0KCXJldHVybjsNCg0K
fQ0KDQppZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiYXV0aHR5cGUiLCBodHRwc3RyaW5nLnN1YnN0
cmluZyhiaW5kZXgrMTAsZWluZGV4KSk7DQoNCmJpbmRleCA9IGh0dHBzdHJpbmcuaW5kZXhPZigi
PGF1dGh1c2VybmFtZT4iLCAwKTsNCg0KaWYoYmluZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxpbmUu
aW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmlu
c2VydEFmdGVyKCJlcnJvciIsICJUaGUgPGF1dGh1c2VybmFtZT4gdGFnIGlzIG1pc3NpbmcgZnJv
bSB0aGUgaHR0cCBwcm9maWxlLiIpOw0KCXJldHVybjsNCg0KfQ0KDQplaW5kZXggPSBodHRwc3Ry
aW5nLmluZGV4T2YoIjwvYXV0aHVzZXJuYW1lPiIsIGJpbmRleCk7DQoNCmlmKGVpbmRleCA8IDAp
IHsNCg0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIsIHN1Y2Nlc3NGbGFn
KTsNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZXJyb3IiLCAiVGhlIDwvYXV0aHVzZXJuYW1l
PiB0YWcgaXMgbWlzc2luZyBmcm9tIHRoZSBodHRwIHByb2ZpbGUuIik7DQoJcmV0dXJuOw0KDQp9
DQoNCmlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJhdXRodXNlcm5hbWUiLCBodHRwc3RyaW5nLnN1
YnN0cmluZyhiaW5kZXgrMTQsZWluZGV4KSk7DQoNCmJpbmRleCA9IGh0dHBzdHJpbmcuaW5kZXhP
ZigiPGF1dGhwYXNzd29yZD4iLCAwKTsNCg0KaWYoYmluZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxp
bmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5l
Lmluc2VydEFmdGVyKCJlcnJvciIsICJUaGUgPGF1dGhwYXNzd29yZD4gdGFnIGlzIG1pc3Npbmcg
ZnJvbSB0aGUgaHR0cCBwcm9maWxlLiIpOw0KCXJldHVybjsNCg0KfQ0KDQplaW5kZXggPSBodHRw
c3RyaW5nLmluZGV4T2YoIjwvYXV0aHBhc3N3b3JkPiIsIGJpbmRleCk7DQoNCmlmKGVpbmRleCA8
IDApIHsNCg0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIsIHN1Y2Nlc3NG
bGFnKTsNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZXJyb3IiLCAiVGhlIDwvYXV0aHBhc3N3
b3JkPiB0YWcgaXMgbWlzc2luZyBmcm9tIHRoZSBodHRwIHByb2ZpbGUuIik7DQoJcmV0dXJuOw0K
DQp9DQoNCmlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJhdXRocGFzc3dvcmQiLCBodHRwc3RyaW5n
LnN1YnN0cmluZyhiaW5kZXgrMTQsZWluZGV4KSk7DQoNCg0KYmluZGV4ID0gaHR0cHN0cmluZy5p
bmRleE9mKCI8ZW5jb2Rpbmd0eXBlPiIsIDApOw0KDQppZihiaW5kZXggPCAwKSB7DQoNCglpZGNQ
aXBlbGluZS5pbnNlcnRBZnRlcigic3VjY2Vzc0ZsYWciLCBzdWNjZXNzRmxhZyk7DQoJaWRjUGlw
ZWxpbmUuaW5zZXJ0QWZ0ZXIoImVycm9yIiwgIlRoZSA8ZW5jb2Rpbmd0eXBlPiB0YWcgaXMgbWlz
c2luZyBmcm9tIHRoZSBodHRwIHByb2ZpbGUuIik7DQoJcmV0dXJuOw0KDQp9DQoNCmVpbmRleCA9
IGh0dHBzdHJpbmcuaW5kZXhPZigiPC9lbmNvZGluZ3R5cGU+IiwgYmluZGV4KTsNCg0KaWYoZWlu
ZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3Vj
Y2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJlcnJvciIsICJUaGUgPC9lbmNv
ZGluZ3R5cGU+IHRhZyBpcyBtaXNzaW5nIGZyb20gdGhlIGh0dHAgcHJvZmlsZS4iKTsNCglyZXR1
cm47DQoNCn0NCg0KU3RyaW5nIGVuY29kaW5nID0gaHR0cHN0cmluZy5zdWJzdHJpbmcoYmluZGV4
KzE0LGVpbmRleCk7DQoNCmlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJlbmNvZGluZ3R5cGUiLGVu
Y29kaW5nKTsNCg0KYmluZGV4ID0gaHR0cHN0cmluZy5pbmRleE9mKCI8aHR0cHVybD4iLCAwKTsN
Cg0KaWYoYmluZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NG
bGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJlcnJvciIsICJU
aGUgPGh0dHB1cmw+IHRhZyBpcyBtaXNzaW5nIGZyb20gdGhlIGh0dHAgcHJvZmlsZS4iKTsNCgly
ZXR1cm47DQoNCn0NCg0KZWluZGV4ID0gaHR0cHN0cmluZy5pbmRleE9mKCI8L2h0dHB1cmw+Iiwg
YmluZGV4KTsNCg0KaWYoZWluZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIo
InN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJl
cnJvciIsICJUaGUgPC9odHRwdXJsPiB0YWcgaXMgbWlzc2luZyBmcm9tIHRoZSBodHRwIHByb2Zp
bGUuIik7DQoJcmV0dXJuOw0KDQp9DQoNCmlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJodHRwdXJs
IiwgaHR0cHN0cmluZy5zdWJzdHJpbmcoYmluZGV4KzksZWluZGV4KSk7DQoNCnN1Y2Nlc3NGbGFn
ID0gInRydWUiOw0KDQppZGNQaXBlbGluZS5pbnNlcnRBZnRlcigic3VjY2Vzc0ZsYWciLCBzdWNj
ZXNzRmxhZyk7DQoNCn0vL2VuZCBvZiB0cnkgYmxvY2sNCg0KY2F0Y2ggKEV4Y2VwdGlvbiBlKSAN
CnsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlLmdldE1lc3NhZ2UoKSk7DQp9DQoNCmZp
bmFsbHkNCnsNCglpZihpZGNQaXBlbGluZSAhPSBudWxsICkgDQoJCWlkY1BpcGVsaW5lLmRlc3Ry
b3koKTsNCn0NCg==</value>
</Values>
