<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">byteArrayInputStreamToString</value>
  <array name="sig" type="value" depth="1">
    <value>[i] object:0:required content</value>
    <value>[o] field:0:required string</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9kZWZpbmUgaW5wdXQgdmFyaWFibGVzDQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IG51bGw7
DQpCeXRlQXJyYXlJbnB1dFN0cmVhbSBpbnB1dFN0cmVhbSA9IG51bGw7IA0KU3RyaW5nQnVmZmVy
IGNvbnRlbnRCdWZmZXIgPSBudWxsOw0KT2JqZWN0IG9iamVjdCA9IG51bGw7DQoNCnRyeXsNCiAN
CmlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCmNvbnRlbnRCdWZmZXIgPSBu
ZXcgU3RyaW5nQnVmZmVyKCk7DQoNCi8vT3V0cHV0IFZhcmlhYmxlcw0KU3RyaW5nIHN1Y2Nlc3NG
bGFnID0gImZhbHNlIjsNCg0KLy8gQ2hlY2sgdG8gc2VlIGlmIHRoZSBpbnRlZ2VyIG9iamVjdCBp
cyBpbiB0aGUgcGlwZWxpbmUNCmlmIChpZGNQaXBlbGluZS5maXJzdCgiY29udGVudCIpKSB7DQoJ
Ly9nZXQgdGhlIGludGVnZXIgdmFsdWUgb2JqZWN0IG91dCBvZiB0aGUgcGlwZWxpbmUNCglpbnB1
dFN0cmVhbSA9IChCeXRlQXJyYXlJbnB1dFN0cmVhbSlpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOw0K
CXdoaWxlKCBpbnB1dFN0cmVhbS5hdmFpbGFibGUoKSAhPSAwICkNCgkJY29udGVudEJ1ZmZlci5h
cHBlbmQoKGNoYXIpaW5wdXRTdHJlYW0ucmVhZCgpKTsNCn0NCg0KLy9pbnNlcnQgdGhlIHN0cmlu
ZyBpbnRvIHRoZSBwaXBlbGluZQ0KaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN0cmluZyIsIGNv
bnRlbnRCdWZmZXIudG9TdHJpbmcoKSk7DQoNCn0vL2VuZCBvZiB0cnkgYmxvY2sNCg0KY2F0Y2gg
KEV4Y2VwdGlvbiBlKQ0Kew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2Fn
ZSgpKTsNCn0NCg0KZmluYWxseXsNCgkvL0Fsd2F5cyBkZXN0cm95IGN1cnNvcnMgdGhhdCB5b3Ug
Y3JlYXRlZA0KCWlmICggaWRjUGlwZWxpbmUgIT0gbnVsbCApDQoJCWlkY1BpcGVsaW5lLmRlc3Ry
b3koKTsNCglpZiAoaW5wdXRTdHJlYW0gIT0gbnVsbCkNCgl0cnkgew0KCQlpbnB1dFN0cmVhbS5j
bG9zZSgpOw0KCX0gY2F0Y2ggKElPRXhjZXB0aW9uIGV4KSB7DQoJCXRocm93IG5ldyBTZXJ2aWNl
RXhjZXB0aW9uKGV4LmdldE1lc3NhZ2UoKSk7IA0KCX0NCn0NCg==</value>
</Values>
