<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readPropertiesFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[o] object:0:required property</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KU3RyaW5n
IHN0ckZpbGVuYW1lID0gbnVsbDsNCmlmIChpZGNQaXBlbGluZS5maXJzdCgiZmlsZW5hbWUiKSkN
CnsNCiAgc3RyRmlsZW5hbWUgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOw0KfQ0K
ZWxzZQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiQ291bGQgbm90IHJlYWQgUHJv
cGVydGllcyBmaWxlLiAgZmlsZW5hbWUgaXMgbnVsbCEiKTsNCn0NCg0KdHJ5DQp7DQogIEZpbGUg
ZmlsZSA9IG5ldyBGaWxlKHN0ckZpbGVuYW1lKTsNCiAgaWYgKGZpbGUuY2FuUmVhZCgpKQ0KICB7
DQogICAgUHJvcGVydGllcyBwcm9wZXJ0eSA9IG5ldyBQcm9wZXJ0aWVzKCk7DQogICAgSW5wdXRT
dHJlYW0gc3RyZWFtID0gbmV3IGphdmEuaW8uQnVmZmVyZWRJbnB1dFN0cmVhbShuZXcgamF2YS5p
by5GaWxlSW5wdXRTdHJlYW0oZmlsZSkpOw0KDQogICAgdHJ5DQogICAgew0KICAgICAgcHJvcGVy
dHkubG9hZChzdHJlYW0pOw0KICAgIH0NCiAgICBmaW5hbGx5DQogICAgew0KICAgICAgc3RyZWFt
LmNsb3NlKCk7DQogICAgfQ0KDQogICAgRW51bWVyYXRpb24gZW51bSA9IHByb3BlcnR5LnByb3Bl
cnR5TmFtZXMoKTsNCiAgICB3aGlsZSAoZW51bS5oYXNNb3JlRWxlbWVudHMoKSkNCiAgICB7DQog
ICAgICBTdHJpbmcgc3RyUHJvcGVydHlOYW1lID0gKFN0cmluZykgZW51bS5uZXh0RWxlbWVudCgp
Ow0KICAgICAgU3RyaW5nIHN0clByb3BlcnR5VmFsdWUgPSAoU3RyaW5nKSBwcm9wZXJ0eS5nZXRQ
cm9wZXJ0eShzdHJQcm9wZXJ0eU5hbWUpOw0KICAgICAgaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIo
c3RyUHJvcGVydHlOYW1lLCBzdHJQcm9wZXJ0eVZhbHVlKTsNCiAgICB9DQoNCiAgICAvLyBQdXQg
ZW50aXJlIHByb3BlcnR5IG9iamVjdCBpbnRvIHRoZSBvdXRwdXQgcGlwZWxpbmUNCiAgICBpZGNQ
aXBlbGluZS5pbnNlcnRBZnRlcigicHJvcGVydHkiLCBwcm9wZXJ0eSk7DQogIH0NCiAgZWxzZQ0K
ICB7DQogICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkNvdWxkIG5vdCByZWFkIHByb3Bl
cnRpZXMgZmlsZTogIiArIHN0ckZpbGVuYW1lKTsNCiAgfQ0KfQ0KY2F0Y2ggKEV4Y2VwdGlvbiBl
KQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRXJyb3IgcmVhZGluZyBwcm9wZXJ0
aWVzIGZpbGU6ICIgKyBlKTsNCn0NCmZpbmFsbHkNCnsNCiAgaWRjUGlwZWxpbmUuZGVzdHJveSgp
Ow0KfQ0KDQo=</value>
</Values>
