<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">checkIsFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[i] field:0:required directory</value>
    <value>[o] field:0:required successFlag</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBudWxsOyANClN0cmluZyBzdWNjZXNzRmxhZyA9IG51
bGw7DQpTdHJpbmcgZmlsZW5hbWUgPSBudWxsLGRpcmVjdG9yeTsNCg0KdHJ5IHsNCgkvL091dHB1
dCBWYXJpYWJsZXMNCglzdWNjZXNzRmxhZz0gImZhbHNlIjsNCgkNCglpZGNQaXBlbGluZSA9IHBp
cGVsaW5lLmdldEN1cnNvcigpOw0KCS8vIENoZWNrIHRvIHNlZSBpZiB0aGUgZmlsZW5hbWUgb2Jq
ZWN0IGlzIGluIHRoZSBwaXBlbGluZQ0KCWlmIChpZGNQaXBlbGluZS5maXJzdCgiZmlsZW5hbWUi
KSkgew0KDQoJCS8vZ2V0IHRoZSBmaWxlbmFtZSBzdHJpbmcgb2JqZWN0IG91dCBvZiB0aGUgcGlw
ZWxpbmUNCgkJZmlsZW5hbWUgPSAoU3RyaW5nKWlkY1BpcGVsaW5lLmdldFZhbHVlKCk7DQoJfQ0K
CS8vaWYgaXQgaXMgbm90IGluIHRoZSBwaXBlbGluZSwgdGhlbiBoYW5kbGUgdGhlIGVycm9yDQoJ
ZWxzZSB7DQoJCXN1Y2Nlc3NGbGFnID0gImZhbHNlIjsNCgkJcmV0dXJuOw0KCX0NCgkNCgkvLyBD
aGVjayB0byBzZWUgaWYgdGhlIGRpcmVjdG9yeSBvYmplY3QgaXMgaW4gdGhlIHBpcGVsaW5lDQoJ
aWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJkaXJlY3RvcnkiKSkgew0KCQkvL2dldCB0aGUgZGlyZWN0
b3J5IHN0cmluZyBvYmplY3Qgb3V0IG9mIHRoZSBwaXBlbGluZQ0KCQlkaXJlY3RvcnkgPSAoU3Ry
aW5nKWlkY1BpcGVsaW5lLmdldFZhbHVlKCk7DQoJfQ0KCS8vaWYgaXQgaXMgbm90IGluIHRoZSBw
aXBlbGluZSwgdGhlbiBoYW5kbGUgdGhlIGVycm9yDQoJZWxzZSB7DQoJCXN1Y2Nlc3NGbGFnID0g
ImZhbHNlIjsNCgkJcmV0dXJuOw0KCX0NCg0KCWZpbGVuYW1lID0gKGRpcmVjdG9yeSArIEZpbGUu
c2VwYXJhdG9yICsgZmlsZW5hbWUpOw0KDQoNCglGaWxlIGZpbGUgPSBuZXcgRmlsZShmaWxlbmFt
ZSk7DQoJaWYoZmlsZS5pc0ZpbGUoKSkgew0KCQlzdWNjZXNzRmxhZyA9ICJ0cnVlIjsNCg0KCQkv
L2luc2VydCB0aGUgc3VjY2Vzc0ZsYWcgaW50byB0aGUgcGlwZWxpbmUNCgkJaWRjUGlwZWxpbmUu
aW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCX0NCgllbHNlIHsNCgkJ
c3VjY2Vzc0ZsYWcgPSAiZmFsc2UiOw0KCQlpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigic3VjY2Vz
c0ZsYWciLCBzdWNjZXNzRmxhZyk7DQoJfQ0KDQp9Y2F0Y2ggKEV4Y2VwdGlvbiBlKSB7DQoJc3Vj
Y2Vzc0ZsYWcgPSAiZmFsc2UiOw0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxh
ZyIsIHN1Y2Nlc3NGbGFnKTsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlLmdldE1lc3Nh
Z2UoKSk7DQp9IGZpbmFsbHkgew0KCS8vQWx3YXlzIGRlc3Ryb3kgY3Vyc29ycyB0aGF0IHlvdSBj
cmVhdGVkDQoJaWYoaWRjUGlwZWxpbmUgIT0gbnVsbCApIA0KCQlpZGNQaXBlbGluZS5kZXN0cm95
KCk7DQp9DQo=</value>
</Values>
