<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readPropertiesFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[o] object:0:required property</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KU3RyaW5n
IHN0ckZpbGVuYW1lID0gbnVsbDsNCmlmIChpZGNQaXBlbGluZS5maXJzdCgiZmlsZW5hbWUiKSkN
CnsNCglzdHJGaWxlbmFtZSA9IChTdHJpbmcpaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsNCn0NCmVs
c2UNCnsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiQ291bGQgbm90IHJlYWQgUHJvcGVy
dGllcyBmaWxlLiAgZmlsZW5hbWUgaXMgbnVsbCEiKTsNCn0NCg0KdHJ5DQp7DQoJRmlsZSBmaWxl
ID0gbmV3IEZpbGUoc3RyRmlsZW5hbWUpOw0KCWlmIChmaWxlLmNhblJlYWQoKSkNCgl7DQoJCVBy
b3BlcnRpZXMgcHJvcGVydHkgPSBuZXcgUHJvcGVydGllcygpOw0KCQlJbnB1dFN0cmVhbSBzdHJl
YW0gPSBuZXcgamF2YS5pby5CdWZmZXJlZElucHV0U3RyZWFtKG5ldyBqYXZhLmlvLkZpbGVJbnB1
dFN0cmVhbShmaWxlKSk7DQoNCgkJdHJ5DQoJCXsNCgkJCXByb3BlcnR5LmxvYWQoc3RyZWFtKTsN
CgkJfQ0KCQlmaW5hbGx5DQoJCXsNCgkJCXN0cmVhbS5jbG9zZSgpOw0KCQl9DQoNCgkJRW51bWVy
YXRpb24gZW51bWVyYXRlID0gcHJvcGVydHkucHJvcGVydHlOYW1lcygpOw0KCQl3aGlsZSAoZW51
bWVyYXRlLmhhc01vcmVFbGVtZW50cygpKQ0KCQl7DQoJCQlTdHJpbmcgc3RyUHJvcGVydHlOYW1l
ID0gKFN0cmluZyllbnVtZXJhdGUubmV4dEVsZW1lbnQoKTsNCgkJCVN0cmluZyBzdHJQcm9wZXJ0
eVZhbHVlID0gKFN0cmluZylwcm9wZXJ0eS5nZXRQcm9wZXJ0eShzdHJQcm9wZXJ0eU5hbWUpOw0K
CQkJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoc3RyUHJvcGVydHlOYW1lLCBzdHJQcm9wZXJ0eVZh
bHVlKTsJCQkJDQoJCX0NCg0KCQkvLyBQdXQgZW50aXJlIHByb3BlcnR5IG9iamVjdCBpbnRvIHRo
ZSBvdXRwdXQgcGlwZWxpbmUNCgkJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInByb3BlcnR5Iiwg
cHJvcGVydHkpOw0KCX0NCgllbHNlDQoJew0KCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigi
Q291bGQgbm90IHJlYWQgcHJvcGVydGllcyBmaWxlOiAiICsgc3RyRmlsZW5hbWUpOw0KCX0NCn0N
CmNhdGNoKCBFeGNlcHRpb24gZSApDQp7DQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkVy
cm9yIHJlYWRpbmcgcHJvcGVydGllcyBmaWxlOiAiICsgZSk7DQp9DQpmaW5hbGx5DQp7DQoJaWRj
UGlwZWxpbmUuZGVzdHJveSgpOw0KfQ0KDQo=</value>
</Values>
