<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getSystemProperty</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqIFNlcnZpY2UgaXMgZGVzaWduZWQgdG8gcmV0dXJuIHRoZSBzcGVjaWZpZWQgc3lzdGVtIHBy
b3BlcnR5Lg0KICAqDQogICogQGF1dGhvciBSeWFuIEpvaG5zdG9uLCBQcm9mZXNzaW9uYWwgU2Vy
dmljZXMsIHdlYk1ldGhvZHMsIEluYy4NCiAgKiBAdmVyc2lvbiAxLjANCiAgKiBNb2RpZmllZCB0
byBjaGVjayBmb3IgZXhpc3Rpbmcgb2YgcHJvcGVydHlMaXN0IGJlZm9yZSBkZWxldGUgKFJvbmFs
ZCBCKQ0KICAqLw0KDQpJRGF0YUN1cnNvciBoQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
DQoNCmhDdXJzb3IuZmlyc3QoInByb3BlcnR5TmFtZSIpOw0KU3RyaW5nIHByb3BlcnR5TmFtZSA9
IChTdHJpbmcpaEN1cnNvci5nZXRWYWx1ZSgpOw0KDQpTdHJpbmcgcHJvcGVydHkgPSBuZXcgU3Ry
aW5nKCk7DQoNCnByb3BlcnR5ID0gU3lzdGVtLmdldFByb3BlcnR5KHByb3BlcnR5TmFtZSwgIk5v
IHByb3BlcnR5IGZvdW5kIik7DQoNCmlmIChoQ3Vyc29yLmZpcnN0KCJwcm9wZXJ0eSIpKQ0KCWhD
dXJzb3IuZGVsZXRlKCk7DQpoQ3Vyc29yLmluc2VydEFmdGVyKCJwcm9wZXJ0eSIsIHByb3BlcnR5
KTsNCgk=</value>
</Values>
