<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">fireCommandExec</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required command</value>
    <value>[o] field:0:required output</value>
    <value>[o] field:0:required successFlag</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CS8vZGVmaW5lIGlucHV0IHZhcmlhYmxlcyANCglJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBp
cGVsaW5lLmdldEN1cnNvcigpOw0KCVN0cmluZyAJc3RyRmlsZUNvbnRlbnQgPSBudWxsOyANCg0K
CS8vT3V0cHV0IFZhcmlhYmxlcyANCglTdHJpbmcgc3VjY2Vzc0ZsYWcgPSAiZmFsc2UiOyANCglT
dHJpbmcgZnVsbENvbW1hbmQgOyAgIA0KIA0KCS8vIENoZWNrIHRvIHNlZSBpZiB0aGUgZnVsbENv
bW1hbmQgb2JqZWN0IGlzIGluIHRoZSBwaXBlbGluZQ0KCWlmIChpZGNQaXBlbGluZS5maXJzdCgi
Y29tbWFuZCIpKQ0KCXsJDQoJCS8vZ2V0IHRoZSBmdWxsQ29tbWFuZCBzdHJlYW0gb3V0IG9mIHRo
ZSBwaXBlbGluZQkJCQkJDQoJCWZ1bGxDb21tYW5kID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0
VmFsdWUoKTsNCgl9DQoJLy9pZiBpdCBpcyBub3QgaW4gdGhlIHBpcGVsaW5lLCB0aGVuIGhhbmRs
ZSB0aGUgZXJyb3INCgllbHNlDQoJew0KCQkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlJl
cXVpcmVkIHBhcmFtZXRlciAnY29tbWFuZCcgbWlzc2luZyIpOw0KCQkJDQoJfQ0KCS8vRXhlY3V0
ZSB0aGUgY29tbWFuZC4gSGFuZGxlIHRoZSBleGNlcHRpb24gaWYgaXQgZmFpbHMuDQoJdHJ5IA0K
CXsNCiAJDQogCQkNCgkJUHJvY2VzcyBjaGlsZCA9ICAgUnVudGltZS5nZXRSdW50aW1lKCkuZXhl
YyhmdWxsQ29tbWFuZCk7DQoJCXN1Y2Nlc3NGbGFnPSJ0cnVlIjsNCgkJDQoJCWludCBjdD0wOw0K
CQlTdHJpbmcgb3V0cHV0PSIiOwkJDQoJCVN0cmluZyBlcnJvcj0iIjsJCQ0KCQlCdWZmZXJlZFJl
YWRlciBpbnB1dCA9ICBuZXcgQnVmZmVyZWRSZWFkZXIobmV3IElucHV0U3RyZWFtUmVhZGVyKGNo
aWxkLmdldEVycm9yU3RyZWFtKCkpKTsNCgkJU3RyaW5nIGxpbmUgPSAiIjsNCgkJaW5wdXQgPSAg
bmV3IEJ1ZmZlcmVkUmVhZGVyKG5ldyBJbnB1dFN0cmVhbVJlYWRlcihjaGlsZC5nZXRJbnB1dFN0
cmVhbSgpKSk7DQoJCWxpbmUgPSBpbnB1dC5yZWFkTGluZSgpOw0KICAgICAJd2hpbGUgKCgobGlu
ZSA9IGlucHV0LnJlYWRMaW5lKCkpICE9IG51bGwpKSB7DQogICAgICAgCQkJCQkJCQkJCQkJb3V0
cHV0PW91dHB1dCtsaW5lOw0KCQkJCQkJCQkJCQkJCX0NCg0KCQlpZGNQaXBlbGluZS5pbnNlcnRB
ZnRlcigib3V0cHV0Iiwgb3V0cHV0KTsNCiAgICAgCWlucHV0LmNsb3NlKCk7DQogCX0gDQoNCglj
YXRjaCAoRXhjZXB0aW9uIGV4KSANCgl7DQoJCXN1Y2Nlc3NGbGFnPSJGYWxzZSI7DQoJCXRocm93
IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGV4KTsNCgkJDQogCX0NCg0KCS8vaW5zZXJ0IHRoZSBzdWNj
ZXNzRmxhZyBpbnRvIHRoZSBwaXBlbGluZQ0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNj
ZXNzRmxhZyIsIHN1Y2Nlc3NGbGFnKTsJDQoNCg0KCS8vQWx3YXlzIGRlc3Ryb3kgY3Vyc29ycyB0
aGF0IHlvdSBjcmVhdGVkDQoJaWRjUGlwZWxpbmUuZGVzdHJveSgpOw0K</value>
</Values>
