<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">zipFiles</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required targetDirectory</value>
    <value>[i] field:0:required zipFileName</value>
    <value>[i] field:1:required archiveList</value>
    <value>[o] field:0:required successFlag</value>
    <value>[o] field:0:required output</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9kZWZpbmUgaW5wdXQgdmFyaWFibGVzDQpJRGF0YUN1cnNvciBpZGMgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNCg0KLy9maW5hbCBTdHJpbmcgZmlsZVR5cGUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KGlkYyAsICJmaWxlVHlwZSIpOw0KU3RyaW5nIHRhcmdldERpcmVjdG9yeSA9IElEYXRhVXRpbC5n
ZXRTdHJpbmcoaWRjICwgInRhcmdldERpcmVjdG9yeSIpOw0KU3RyaW5nIHppcEZpbGVOYW1lID0g
SURhdGFVdGlsLmdldFN0cmluZyhpZGMgLCAiemlwRmlsZU5hbWUiKTsNClN0cmluZ1tdIGNoaWxk
cmVuID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KGlkYyAsICJhcmNoaXZlTGlzdCIpOw0KU3Ry
aW5nIG91dHB1dCA9ICIiOw0KU3RyaW5nIHN1Y2Nlc3NGbGFnID0gIiI7DQoNCnppcEZpbGVOYW1l
ID0gdGFyZ2V0RGlyZWN0b3J5ICsgJ1xcJyArIHppcEZpbGVOYW1lIDsNCg0KdHJ5CXsNCg0KCWJ5
dGVbXSBidWZmZXIgPSBuZXcgYnl0ZVsxODAyNF07DQoNCglaaXBPdXRwdXRTdHJlYW0gb3V0ID0g
bmV3IFppcE91dHB1dFN0cmVhbShuZXcgRmlsZU91dHB1dFN0cmVhbSh6aXBGaWxlTmFtZSkpOw0K
DQoJLy8gU2V0IHRoZSBjb21wcmVzc2lvbiByYXRpbw0KCW91dC5zZXRMZXZlbChEZWZsYXRlci5E
RUZBVUxUX0NPTVBSRVNTSU9OKTsNCg0KCS8vIGl0ZXJhdGUgdGhyb3VnaCB0aGUgYXJyYXkgb2Yg
ZmlsZXMsIGFkZGluZyBlYWNoIHRvIHRoZSB6aXAgZmlsZQ0KCWZvciAoaW50IGkgPSAwOyBpIDwg
Y2hpbGRyZW4ubGVuZ3RoOyBpKyspIHsNCg0KCQkvL2lmIChjaGlsZHJlbltpXS5sZW5ndGggPjAp
IHsNCgkJLy8gQXNzb2NpYXRlIGEgZmlsZSBpbnB1dCBzdHJlYW0gZm9yIHRoZSBjdXJyZW50IGZp
bGUNCgkJU3RyaW5nIHdob2xlTmFtZSA9IHRhcmdldERpcmVjdG9yeSArICJcXCIgKyBjaGlsZHJl
bltpXTsNCg0KCQlGaWxlSW5wdXRTdHJlYW0gaW4gPSBuZXcgRmlsZUlucHV0U3RyZWFtKHdob2xl
TmFtZSk7DQoNCgkJLy8gQWRkIFpJUCBlbnRyeSB0byBvdXRwdXQgc3RyZWFtLg0KCQlvdXQucHV0
TmV4dEVudHJ5KG5ldyBaaXBFbnRyeShjaGlsZHJlbltpXSkpOw0KDQoJCS8vIFRyYW5zZmVyIGJ5
dGVzIGZyb20gdGhlIGN1cnJlbnQgZmlsZSB0byB0aGUgWklQIGZpbGUNCgkJb3V0LndyaXRlKGJ1
ZmZlciwgMCwgaW4ucmVhZChidWZmZXIpKTsNCg0KCQlpbnQgbGVuOw0KCQl3aGlsZSAoKGxlbiA9
IGluLnJlYWQoYnVmZmVyKSkgPiAwKSANCgkJew0KCQkJb3V0LndyaXRlKGJ1ZmZlciwgMCwgbGVu
KTsNCgkJfQ0KDQoJCS8vIENsb3NlIHRoZSBjdXJyZW50IGVudHJ5DQoJCW91dC5jbG9zZUVudHJ5
KCk7DQoNCgkJLy8gQ2xvc2UgdGhlIGN1cnJlbnQgZmlsZSBpbnB1dCBzdHJlYW0NCgkJaW4uY2xv
c2UoKTsNCgkJLy99IC8vaWYgY2xvc2UgZm9yIGxlbmd0aCBjaGVjaw0KDQoJfS8vZm9yIGNsb3N1
cmUNCgkvLyBDbG9zZSB0aGUgWmlwT3V0UHV0U3RyZWFtDQoJb3V0LmNsb3NlKCk7DQoNCglzdWNj
ZXNzRmxhZz0idHJ1ZSI7DQoJb3V0cHV0ID0gIiBaaXAgZmlsZSBpcyBjcmVhdGVkICI7DQoJCQ0K
fWNhdGNoIChJbGxlZ2FsQXJndW1lbnRFeGNlcHRpb24gaWFlKSB7DQoJc3VjY2Vzc0ZsYWc9ImZh
bHNlIjsNCglvdXRwdXQgPSBpYWUuZ2V0TWVzc2FnZSgpOw0KfQ0KY2F0Y2ggKEZpbGVOb3RGb3Vu
ZEV4Y2VwdGlvbiBmbmZlKSB7DQoJc3VjY2Vzc0ZsYWc9ImZhbHNlIjsNCglvdXRwdXQgPSBmbmZl
LmdldE1lc3NhZ2UoKTsNCn0NCmNhdGNoIChJT0V4Y2VwdGlvbiBpb2UpDQp7DQoJc3VjY2Vzc0Zs
YWc9ImZhbHNlIjsNCglvdXRwdXQgPWlvZS5nZXRNZXNzYWdlKCk7DQp9Y2F0Y2ggKEV4Y2VwdGlv
biBleCkJDQp7DQoJc3VjY2Vzc0ZsYWc9ImZhbHNlIjsNCglpZiAoZXguZ2V0TWVzc2FnZSgpPT1u
dWxsKQ0KCQlvdXRwdXQgPSBvdXRwdXQgOw0KCWVsc2UNCgkJb3V0cHV0ID0gb3V0cHV0ICsgZXgu
Z2V0TWVzc2FnZSgpOw0KfWZpbmFsbHkJew0KCS8vaW5zZXJ0IHRoZSBzdWNjZXNzRmxhZyBpbnRv
IHRoZSBwaXBlbGluZQ0KCWlkYy5pbnNlcnRBZnRlcigic3VjY2Vzc0ZsYWciLCBzdWNjZXNzRmxh
Zyk7DQoJaWRjLmluc2VydEFmdGVyKCJvdXRwdXQiLCBvdXRwdXQpOw0KCQ0KCS8vQWx3YXlzIGRl
c3Ryb3kgY3Vyc29ycyB0aGF0IHlvdSBjcmVhdGVkDQoJaWRjLmRlc3Ryb3koKTsNCn0NCg==</value>
</Values>
