<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">extractZipFiles</value>
  <array name="sig" type="value" depth="1">
    <value>[i] object:0:required inputbytes</value>
    <value>[o] field:1:required filescontent</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBudWxsOw0KU3RyaW5nW10gZmlsZXNDb250ZW50Ow0K
WmlwSW5wdXRTdHJlYW0gemlwaW5wdXRzdHJlYW07DQpieXRlW10gaW5wdXRCeXRlczsNCmludCBq
ID0gMDsNCmludCBudW1iZXJFbnRyaWVzID0gMDsNCg0KdHJ5IHsNCglpZGNQaXBlbGluZSA9IHBp
cGVsaW5lLmdldEN1cnNvcigpOw0KaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJpbnB1dGJ5dGVzIikp
IHsNCgkvL2dldCB0aGUgaW5wdXRCeXRlcyB2YWx1ZSBvYmplY3Qgb3V0IG9mIHRoZSBwaXBlbGlu
ZQ0KCWlucHV0Qnl0ZXMgPSAoYnl0ZVtdKWlkY1BpcGVsaW5lLmdldFZhbHVlKCk7DQp9DQovL2lm
IGl0IGlzIG5vdCBpbiB0aGUgcGlwZWxpbmUsIHRoZW4gaGFuZGxlIHRoZSBlcnJvcg0KZWxzZSB7
DQoNCg0KCS8vQWx3YXlzIGRlc3Ryb3kgY3Vyc29ycyB0aGF0IHlvdSBjcmVhdGVkDQoJaWRjUGlw
ZWxpbmUuZGVzdHJveSgpOw0KDQoJcmV0dXJuOw0KfQ0KDQp6aXBpbnB1dHN0cmVhbSA9IG5ldyBa
aXBJbnB1dFN0cmVhbShuZXcgQnl0ZUFycmF5SW5wdXRTdHJlYW0oaW5wdXRCeXRlcykpOw0KDQp0
cnl7DQoNCglaaXBFbnRyeSB6aXBFbnRyeSA9IHppcGlucHV0c3RyZWFtLmdldE5leHRFbnRyeSgp
Ow0KDQoJd2hpbGUgKHppcEVudHJ5ICE9IG51bGwpIA0KCXsNCgkJaWYgKHppcEVudHJ5LmlzRGly
ZWN0b3J5KCkpIHsNCgkJCWNvbnRpbnVlOw0KCQl9DQoJCW51bWJlckVudHJpZXMrKzsNCgkJemlw
aW5wdXRzdHJlYW0uY2xvc2VFbnRyeSgpOw0KCQl6aXBFbnRyeSA9IHppcGlucHV0c3RyZWFtLmdl
dE5leHRFbnRyeSgpOw0KCX0NCg0KCXppcGlucHV0c3RyZWFtLmNsb3NlKCk7DQoJDQp9IGNhdGNo
IChqYXZhLmxhbmcuRXhjZXB0aW9uIGUpIHsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihl
LmdldE1lc3NhZ2UoKSk7DQp9DQogDQpmaWxlc0NvbnRlbnQgPSBuZXcgU3RyaW5nW251bWJlckVu
dHJpZXNdOw0KZm9yIChpbnQgdCA9IDA7IHQgPCBudW1iZXJFbnRyaWVzOyB0KyspIHsNCglmaWxl
c0NvbnRlbnRbdF0gPSAiIjsNCn0NCg0KemlwaW5wdXRzdHJlYW0gPSBuZXcgWmlwSW5wdXRTdHJl
YW0obmV3IEJ5dGVBcnJheUlucHV0U3RyZWFtKGlucHV0Qnl0ZXMpKTsNCg0KdHJ5IHsNCg0KCVpp
cEVudHJ5IHppcGVudHJ5ID0gDQp6aXBpbnB1dHN0cmVhbS5nZXROZXh0RW50cnkoKTsNCgkNCgl3
aGlsZSh6aXBlbnRyeSAhPSBudWxsKSB7DQoNCgkJaWYgKHppcGVudHJ5LmlzRGlyZWN0b3J5KCkp
IHsNCgkJCWNvbnRpbnVlOw0KCQl9DQoJCQkNCgkJaW50IHZhbHVlOw0KDQoJCXdoaWxlICgodmFs
dWUgPSB6aXBpbnB1dHN0cmVhbS5yZWFkKCkpICE9IC0xKSB7DQoJCQlmaWxlc0NvbnRlbnRbal0g
Kz0gKGNoYXIpdmFsdWU7DQoJCX0NCgkNCgkJaisrOw0KCQl6aXBpbnB1dHN0cmVhbS5jbG9zZUVu
dHJ5KCk7DQoJCXppcGVudHJ5ID0gDQp6aXBpbnB1dHN0cmVhbS5nZXROZXh0RW50cnkoKTsNCgl9
DQoNCgl6aXBpbnB1dHN0cmVhbS5jbG9zZSgpOw0KDQp9IGNhdGNoIChqYXZhLmxhbmcuRXhjZXB0
aW9uIGUpIHsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlLmdldE1lc3NhZ2UoKSk7DQp9
DQoNCmlmIChmaWxlc0NvbnRlbnQgIT0gbnVsbCkgew0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVy
KCJmaWxlc2NvbnRlbnQiLGZpbGVzQ29udGVudCk7CQ0KfQ0KDQp9Y2F0Y2ggKGphdmEubGFuZy5F
eGNlcHRpb24gZXgpIHsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihleC5nZXRNZXNzYWdl
KCkpOw0KfSBmaW5hbGx5IHsNCglpZihpZGNQaXBlbGluZSAhPSBudWxsICkgew0KCQlpZGNQaXBl
bGluZS5kZXN0cm95KCk7DQoJfQ0KfQ0K</value>
</Values>
