<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">searchableIDataLookup</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required searchValue</value>
    <value>[i] record:0:required searchableIData</value>
    <value>[o] record:0:required boundNode</value>
    <value>[o] - field:0:required CustomSchamaNS</value>
    <value>[o] field:0:required searchValueFound</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gZ2V0IGEgY3Vyc29yIG9uIHRoZSBwaXBlbGluZQ0KSURhdGFDdXJzb3IgaWRjID0gcGlwZWxp
bmUuZ2V0Q3Vyc29yKCk7DQoNCi8vZGVmaW5lIHdvcmtpbmcgdmFyaWFibGVzDQpib29sZWFuIHNl
YXJjaFZhbHVlRm91bmQgPSBmYWxzZTsNCklEYXRhIHJlc3VsdHJlYyA9IG51bGw7DQpTdHJpbmcg
c2VhcmNoVmFsdWUgPSBudWxsOw0KSURhdGEgc2VhcmNoYWJsZUlEYXRhID0gSURhdGFGYWN0b3J5
LmNyZWF0ZSgpOw0KSURhdGFDdXJzb3IgaWRjU0lEID0gbnVsbDsNCg0KdHJ5IHsNCg0KCS8vZ2V0
IHRoZSBzZWFyY2hhYmxlSURhdGEgZnJvbSB0aGUgcGlwZWxpbmUgYW5kIHJldHVybiBhbiBlcnJv
ciBpZiBpdCBpcyBub3QgZm91bmQNCglpZiAoaWRjLmZpcnN0KCJzZWFyY2hhYmxlSURhdGEiKSkg
ew0KCQlzZWFyY2hhYmxlSURhdGEgPSBJRGF0YVV0aWwuZ2V0SURhdGEoaWRjLCAic2VhcmNoYWJs
ZUlEYXRhIik7DQoJCWlkY1NJRCA9IHNlYXJjaGFibGVJRGF0YS5nZXRDdXJzb3IoKTsNCgl9IGVs
c2Ugew0KCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbiAoIkVSUk9SOiBzZWFyY2hhYmxlSURh
dGEgbXVzdCBiZSBwcm92aWRlZCIpOw0KCX0NCg0KCS8vZ2V0IHRoZSBzZWFyY2hWYWx1ZSBmcm9t
IHRoZSBwaXBlbGluZSBhbmQgcmV0dXJuIGFuIGVycm9yIGlmIGl0IGlzIG5vdCBmb3VuZA0KCWlm
IChpZGMuZmlyc3QoInNlYXJjaFZhbHVlIikpIHsNCgkJc2VhcmNoVmFsdWUgPSAoU3RyaW5nKUlE
YXRhVXRpbC5nZXQoaWRjLCAic2VhcmNoVmFsdWUiKTsNCgl9IGVsc2Ugew0KCQl0aHJvdyBuZXcg
U2VydmljZUV4Y2VwdGlvbigiRVJST1I6IHNlYXJjaFZhbHVlIG11c3QgYmUgcHJvdmlkZWQiKTsN
Cgl9DQoNCgkvL2F0dGVtcHQgdG8gbG9jYXRlIHRoZSBrZXkgdGhhdCBoYXMgdGhlIHZhbHVlIG9m
IHNlYXJjaFZhbHVlIGluIHRoZSBzZWFyY2hhYmxlSURhdGEgYW5kIHB1dCB0aGUgdmFsdWUgb2Yg
dGhhdCBrZXkgb24gdGhlIG91dHB1dCBwaXBlbG5lIGFzIGJvdW5kTm9kZQ0KCWlmIChpZGNTSUQu
Zmlyc3Qoc2VhcmNoVmFsdWUpKSB7DQoJCXNlYXJjaFZhbHVlRm91bmQgPSB0cnVlOw0KCQlyZXN1
bHRyZWMgPSAoSURhdGEpSURhdGFVdGlsLmdldChpZGNTSUQsIHNlYXJjaFZhbHVlKTsNCgkJaWRj
Lmluc2VydEFmdGVyKCJib3VuZE5vZGUiLCByZXN1bHRyZWMpOw0KCX0gZWxzZSB7DQoJCWlkYy5p
bnNlcnRBZnRlcigiYm91bmROb2RlIiwgcmVzdWx0cmVjKTsNCgkJc2VhcmNoVmFsdWVGb3VuZCA9
IGZhbHNlOw0KCX0NCg0KCS8vZmluaXNoZWQgd2l0aCB0aGUgaWRjU0lEIGN1cnNvciwgc28gZGVz
dHJveSBpdA0KCWlkY1NJRC5kZXN0cm95KCk7DQoNCgkvL3B1dCB0aGUgc2VhcmNoVmFsdWVGb3Vu
ZCBvbiB0aGUgb3V0cHV0IHBpcGVsaW5lDQoJaWRjLmluc2VydEFmdGVyKCJzZWFyY2hWYWx1ZUZv
dW5kIiwgU3RyaW5nLnZhbHVlT2Yoc2VhcmNoVmFsdWVGb3VuZCkpOw0KDQovL2hhbmRsZSBleGNl
cHRpb25zDQp9IGNhdGNoIChFeGNlcHRpb24gZSkgew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0
aW9uICgiRXJyb3I6ICAiICsgZS50b1N0cmluZygpKTsNCn0gZmluYWxseSB7DQoJaWRjLmRlc3Ry
b3koKTsNCn0NCgkNCg==</value>
</Values>
