<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">fileLastModified</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[i] field:0:required directory</value>
    <value>[o] field:0:required successFlag</value>
    <value>[o] field:0:required lastModifiedDate</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBudWxsOyANClN0cmluZyBmaWxlbmFtZSwgZGlyZWN0
b3J5LCBsb25nRmlsZW5hbWU7DQpTdHJpbmcgc3VjY2Vzc0ZsYWcgPSBudWxsOw0KU3RyaW5nIGxh
c3RNb2RpZmllZERhdGUgPSBudWxsOw0KbG9uZyBsb25nRGF0ZTsNCg0KdHJ5IHsNCgkvL091dHB1
dCBWYXJpYWJsZXMNCglzdWNjZXNzRmxhZz0gImZhbHNlIjsNCg0KCWlkY1BpcGVsaW5lID0gcGlw
ZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCgkvLyBDaGVjayB0byBzZWUgaWYgdGhlIGZpbGVuYW1lIG9i
amVjdCBpcyBpbiB0aGUgcGlwZWxpbmUNCglpZiAoaWRjUGlwZWxpbmUuZmlyc3QoImZpbGVuYW1l
IikpIHsNCg0KCQkvL2dldCB0aGUgZmlsZW5hbWUgc3RyaW5nIG9iamVjdCBvdXQgb2YgdGhlIHBp
cGVsaW5lDQoJCWZpbGVuYW1lID0gKFN0cmluZylpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOw0KCX0N
CgkvL2lmIGl0IGlzIG5vdCBpbiB0aGUgcGlwZWxpbmUsIHRoZW4gaGFuZGxlIHRoZSBlcnJvcg0K
CWVsc2Ugew0KCQlzdWNjZXNzRmxhZyA9ICJmYWxzZSI7DQoJCXJldHVybjsNCgl9DQoNCg0KCS8v
IENoZWNrIHRvIHNlZSBpZiB0aGUgZGlyZWN0b3J5IG9iamVjdCBpcyBpbiB0aGUgcGlwZWxpbmUN
CglpZiAoaWRjUGlwZWxpbmUuZmlyc3QoImRpcmVjdG9yeSIpKSB7DQoJCS8vZ2V0IHRoZSBkaXJl
Y3Rvcnkgc3RyaW5nIG9iamVjdCBvdXQgb2YgdGhlIHBpcGVsaW5lDQoJCWRpcmVjdG9yeSA9IChT
dHJpbmcpaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsNCgl9DQoJLy9pZiBpdCBpcyBub3QgaW4gdGhl
IHBpcGVsaW5lLCB0aGVuIGhhbmRsZSB0aGUgZXJyb3INCgllbHNlIHsNCgkJc3VjY2Vzc0ZsYWcg
PSAiZmFsc2UiOw0KCQlyZXR1cm47DQoJfQ0KDQoJbG9uZ0ZpbGVuYW1lID0gKGRpcmVjdG9yeSAr
IEZpbGUuc2VwYXJhdG9yICsgZmlsZW5hbWUpOw0KDQoJLy9Bc3NpZ24gZnVsbCBwYXRoIG5hbWUg
dG8gYSBmaWxlIG9iamVjdA0KCUZpbGUgbG9jYWxGaWxlID0gbmV3IEZpbGUobG9uZ0ZpbGVuYW1l
KTsNCg0KCS8vVHJ5IHRvIGRlbGV0ZSB0aGUgZmlsZQ0KCS8vQ2hlY2sgaXMgYSBkaXJlY3Rvcnkg
d2FzIGVudGVyZWQNCgkNCglpZiAobG9jYWxGaWxlLmlzRGlyZWN0b3J5KCkpIHsNCgkJc3VjY2Vz
c0ZsYWcgPSAiZmFsc2UiOw0KCX0gZWxzZSBpZiAoIWxvY2FsRmlsZS5leGlzdHMoKSkgeyAJLy9D
aGVjayBpZiB0aGUgZmlsZSBkb2Vzbid0IGV4aXN0DQoJCXN1Y2Nlc3NGbGFnID0gImZhbHNlIjsN
Cgl9IGVsc2UgaWYgKCFsb2NhbEZpbGUuY2FuV3JpdGUoKSkgeyAgICAJLy9jaGVjayBpZiB5b3Ug
Y2FuIHdyaXRlIHRvIGZpbGUNCgkJc3VjY2Vzc0ZsYWcgPSAiZmFsc2UiOw0KCX0gZWxzZSB7IAkJ
CQkvL0dldCB0aGUgbGFzdCBtb2RpZmllZCBkYXRlDQoJCWxvbmdEYXRlID0gbG9jYWxGaWxlLmxh
c3RNb2RpZmllZCgpOw0KCQkvL2xhc3RNb2RpZmllZERhdGUgPSBTdHJpbmcudmFsdWVPZihsb25n
RGF0ZSk7DQoJCWphdmEudXRpbC5EYXRlIGRhdGUyID0gbmV3IGphdmEudXRpbC5EYXRlKGxvbmdE
YXRlKTsgDQoJCWphdmEudGV4dC5TaW1wbGVEYXRlRm9ybWF0IGRhdGVmb3JtYXRZWVlZTU1ERCA9
IG5ldyBTaW1wbGVEYXRlRm9ybWF0KCJ5eXl5LU1NLWRkIik7DQoJCWxhc3RNb2RpZmllZERhdGUg
PSBuZXcgU3RyaW5nKCBkYXRlZm9ybWF0WVlZWU1NREQuZm9ybWF0KCBkYXRlMiApICk7CQ0KCQlz
dWNjZXNzRmxhZyA9ICJ0cnVlIjsNCgl9DQogCS8vaW5zZXJ0IHRoZSBzdWNjZXNzRmxhZyBpbnRv
IHRoZSBwaXBlbGluZQ0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIsIHN1
Y2Nlc3NGbGFnKTsNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigibGFzdE1vZGlmaWVkRGF0ZSIs
IGxhc3RNb2RpZmllZERhdGUgKTsNCn0vL0NhdGNoIGFueSBvdGhlciBlcnJvcidzDQpjYXRjaCAo
RXhjZXB0aW9uIGUpIHsNCglzdWNjZXNzRmxhZyA9ICJmYWxzZSI7DQoJaWRjUGlwZWxpbmUuaW5z
ZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCXRocm93IG5ldyBTZXJ2aWNl
RXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsNCn0gZmluYWxseSB7DQoJLy9BbHdheXMgZGVzdHJv
eSBjdXJzb3JzIHRoYXQgeW91IGNyZWF0ZWQNCglpZihpZGNQaXBlbGluZSAhPSBudWxsICkgDQoJ
CWlkY1BpcGVsaW5lLmRlc3Ryb3koKTsNCn0NCg0KDQo=</value>
</Values>
