<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">deleteFileWithAbsolutePath</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[o] field:0:required successFlag</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9kZWZpbmUgaW5wdXQgdmFyaWFibGVzDQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IG51bGw7
IA0KU3RyaW5nIGZpbGVwYXRoYW5kbmFtZTsNClN0cmluZyBzdWNjZXNzRmxhZyA9IG51bGw7DQp0
cnkgew0KCS8vT3V0cHV0IFZhcmlhYmxlcw0KCXN1Y2Nlc3NGbGFnPSAiZmFsc2UiOw0KDQoJaWRj
UGlwZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCg0KCS8vIENoZWNrIHRvIHNlZSBpZiB0
aGUgZmlsZW5hbWUgb2JqZWN0IGlzIGluIHRoZSBwaXBlbGluZQ0KCWlmIChpZGNQaXBlbGluZS5m
aXJzdCgiZmlsZXBhdGhhbmRuYW1lIikpIHsNCg0KCQkvL2dldCB0aGUgZmlsZW5hbWUgc3RyaW5n
IG9iamVjdCBvdXQgb2YgdGhlIHBpcGVsaW5lDQoJCWZpbGVwYXRoYW5kbmFtZSA9IChTdHJpbmcp
aWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsNCgl9DQoJLy9pZiBpdCBpcyBub3QgaW4gdGhlIHBpcGVs
aW5lLCB0aGVuIGhhbmRsZSB0aGUgZXJyb3INCgllbHNlIHsNCgkJc3VjY2Vzc0ZsYWcgPSAiZmFs
c2UiOw0KCQlyZXR1cm47DQoJfQ0KDQoJDQoJLy9Bc3NpZ24gZnVsbCBwYXRoIG5hbWUgdG8gYSBm
aWxlIG9iamVjdA0KCUZpbGUgbG9jYWxGaWxlID0gbmV3IEZpbGUoZmlsZXBhdGhhbmRuYW1lKTsN
Cg0KCS8vVHJ5IHRvIGRlbGV0ZSB0aGUgZmlsZQ0KCS8vQ2hlY2sgaXMgYSBkaXJlY3Rvcnkgd2Fz
IGVudGVyZWQNCgkNCglpZiAobG9jYWxGaWxlLmlzRGlyZWN0b3J5KCkpIHsNCgkJc3VjY2Vzc0Zs
YWcgPSAiZmFsc2UiOw0KCX0gZWxzZSBpZiAoIWxvY2FsRmlsZS5leGlzdHMoKSkgeyAJLy9DaGVj
ayBpZiB0aGUgZmlsZSBkb2Vzbid0IGV4aXN0DQoJCXN1Y2Nlc3NGbGFnID0gImZhbHNlIjsNCgl9
IGVsc2UgaWYgKCFsb2NhbEZpbGUuY2FuV3JpdGUoKSkgeyAgICAJLy9jaGVjayBpZiB5b3UgY2Fu
IHdyaXRlIHRvIGZpbGUNCgkJc3VjY2Vzc0ZsYWcgPSAiZmFsc2UiOw0KCX0gZWxzZSB7IAkJCQkv
L0ZpbGUgY2FuIGJlIGRlbGV0ZWQNCgkJbG9jYWxGaWxlLmRlbGV0ZSgpOw0KCQlzdWNjZXNzRmxh
ZyA9ICJ0cnVlIjsNCgl9DQogLy9pbnNlcnQgdGhlIHN1Y2Nlc3NGbGFnIGludG8gdGhlIHBpcGVs
aW5lDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcp
Ow0KfQ0KLy9DYXRjaCBhbnkgb3RoZXIgZXJyb3Incw0KY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7DQoJ
c3VjY2Vzc0ZsYWcgPSAiZmFsc2UiOw0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNz
RmxhZyIsIHN1Y2Nlc3NGbGFnKTsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlLmdldE1l
c3NhZ2UoKSk7DQp9IGZpbmFsbHkgew0KDQoJLy9BbHdheXMgZGVzdHJveSBjdXJzb3JzIHRoYXQg
eW91IGNyZWF0ZWQNCglpZihpZGNQaXBlbGluZSAhPSBudWxsICkgDQoJCWlkY1BpcGVsaW5lLmRl
c3Ryb3koKTsNCg0KfQ0KDQo=</value>
</Values>
