<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parseFTPURL</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required string</value>
    <value>[o] field:0:required serverhost</value>
    <value>[o] field:0:required serverport</value>
    <value>[o] field:0:required dataport</value>
    <value>[o] field:0:required encoding</value>
    <value>[o] field:0:required timeout</value>
    <value>[o] field:0:required username</value>
    <value>[o] field:0:required password</value>
    <value>[o] field:0:required path</value>
    <value>[o] field:0:required filename</value>
    <value>[o] field:0:required error</value>
    <value>[o] field:0:required successFlag</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">U3RyaW5nIGZ0cHN0cmluZzsNCmludCBiaW5kZXg7DQppbnQgZWluZGV4Ow0KDQoNClN0cmluZyBz
dWNjZXNzRmxhZyA9ICJmYWxzZSI7DQoNCg0KSURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBudWxs
Ow0KDQp0cnl7DQoNCmlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCmlmIChp
ZGNQaXBlbGluZS5maXJzdCgic3RyaW5nIikpIHsNCg0KCWZ0cHN0cmluZyA9IChTdHJpbmcpaWRj
UGlwZWxpbmUuZ2V0VmFsdWUoKTsNCg0KfQ0KDQplbHNlIHsNCg0KDQoNCglpZGNQaXBlbGluZS5p
bnNlcnRBZnRlcigic3VjY2Vzc0ZsYWciLCBzdWNjZXNzRmxhZyk7DQoJaWRjUGlwZWxpbmUuaW5z
ZXJ0QWZ0ZXIoImVycm9yIiwgIk5vIGlucHV0IHN0cmluZyBmb3IgZnRwIHVybC4iKTsNCg0KCXJl
dHVybjsNCg0KfQ0KDQoNCmZ0cHN0cmluZyA9IGZ0cHN0cmluZy50cmltKCk7DQoNCmJpbmRleCA9
IGZ0cHN0cmluZy5pbmRleE9mKCI8c2VydmVyaG9zdD4iLCAwKTsNCg0KaWYoYmluZGV4IDwgMCkg
ew0KDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcp
Ow0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJlcnJvciIsICJUaGUgPHNlcnZlcmhvc3Q+IHRh
ZyBpcyBtaXNzaW5nIGZyb20gdGhlIGh0dHAgcHJvZmlsZS4iKTsNCg0KCXJldHVybjsNCg0KfQ0K
DQplaW5kZXggPSBmdHBzdHJpbmcuaW5kZXhPZigiPC9zZXJ2ZXJob3N0PiIsIDApOw0KDQppZihl
aW5kZXggPCAwKSB7DQoNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigic3VjY2Vzc0ZsYWciLCBz
dWNjZXNzRmxhZyk7DQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoImVycm9yIiwgIlRoZSA8L3Nl
cnZlcmhvc3Q+IHRhZyBpcyBtaXNzaW5nIGZyb20gYmVnaW5pbmcgb2YgdGhlIGh0dHAgcHJvZmls
ZS4iKTsNCg0KCXJldHVybjsNCg0KfQ0KDQppZGNQaXBlbGluZS5pbnNlcnRBZnRlcigic2VydmVy
aG9zdCIsIGZ0cHN0cmluZy5zdWJzdHJpbmcoYmluZGV4KzEyLGVpbmRleCkpOw0KDQpiaW5kZXgg
PSBmdHBzdHJpbmcuaW5kZXhPZigiPHNlcnZlcnBvcnQ+IiwgMCk7DQoNCmlmKGJpbmRleCA8IDAp
IHsNCg0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIsIHN1Y2Nlc3NGbGFn
KTsNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZXJyb3IiLCAiVGhlIDxzZXJ2ZXJwb3J0PiB0
YWcgaXMgbWlzc2luZyBmcm9tIHRoZSBodHRwIHByb2ZpbGUuIik7DQoNCglyZXR1cm47DQoNCn0N
Cg0KZWluZGV4ID0gZnRwc3RyaW5nLmluZGV4T2YoIjwvc2VydmVycG9ydD4iLCAwKTsNCg0KaWYo
ZWluZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwg
c3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJlcnJvciIsICJUaGUgPC9z
ZXJ2ZXJwb3J0PiB0YWcgaXMgbWlzc2luZyBmcm9tIGJlZ2luaW5nIG9mIHRoZSBodHRwIHByb2Zp
bGUuIik7DQoNCglyZXR1cm47DQoNCn0NCg0KaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInNlcnZl
cnBvcnQiLCBmdHBzdHJpbmcuc3Vic3RyaW5nKGJpbmRleCsxMixlaW5kZXgpKTsNCg0KYmluZGV4
ID0gZnRwc3RyaW5nLmluZGV4T2YoIjxkYXRhcG9ydD4iLCAwKTsNCg0KaWYoYmluZGV4IDwgMCkg
ew0KDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcp
Ow0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJlcnJvciIsICJUaGUgPGRhdGFwb3J0PiB0YWcg
aXMgbWlzc2luZyBmcm9tIHRoZSBodHRwIHByb2ZpbGUuIik7DQoNCglyZXR1cm47DQoNCn0NCg0K
ZWluZGV4ID0gZnRwc3RyaW5nLmluZGV4T2YoIjwvZGF0YXBvcnQ+IiwgMCk7DQoNCmlmKGVpbmRl
eCA8IDApIHsNCg0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIsIHN1Y2Nl
c3NGbGFnKTsNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZXJyb3IiLCAiVGhlIDwvZGF0YXBv
cnQ+IHRhZyBpcyBtaXNzaW5nIGZyb20gYmVnaW5pbmcgb2YgdGhlIGh0dHAgcHJvZmlsZS4iKTsN
Cg0KCXJldHVybjsNCg0KfQ0KDQppZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZGF0YXBvcnQiLCBm
dHBzdHJpbmcuc3Vic3RyaW5nKGJpbmRleCsxMCxlaW5kZXgpKTsNCg0KYmluZGV4ID0gZnRwc3Ry
aW5nLmluZGV4T2YoIjxlbmNvZGluZz4iLCAwKTsNCg0KaWYoYmluZGV4IDwgMCkgew0KDQoJaWRj
UGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlkY1Bp
cGVsaW5lLmluc2VydEFmdGVyKCJlcnJvciIsICJUaGUgPGVuY29kaW5nPiB0YWcgaXMgbWlzc2lu
ZyBmcm9tIHRoZSBodHRwIHByb2ZpbGUuIik7DQoNCglyZXR1cm47DQoNCn0NCg0KZWluZGV4ID0g
ZnRwc3RyaW5nLmluZGV4T2YoIjwvZW5jb2Rpbmc+IiwgMCk7DQoNCmlmKGVpbmRleCA8IDApIHsN
Cg0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIsIHN1Y2Nlc3NGbGFnKTsN
CglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZXJyb3IiLCAiVGhlIDwvZW5jb2Rpbmc+IHRhZyBp
cyBtaXNzaW5nIGZyb20gYmVnaW5pbmcgb2YgdGhlIGh0dHAgcHJvZmlsZS4iKTsNCg0KCXJldHVy
bjsNCg0KfQ0KDQoNClN0cmluZyBlbmNvZGluZyA9IGZ0cHN0cmluZy5zdWJzdHJpbmcoYmluZGV4
KzEwLGVpbmRleCk7DQoNCmlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJlbmNvZGluZyIsIGVuY29k
aW5nKTsNCg0KYmluZGV4ID0gZnRwc3RyaW5nLmluZGV4T2YoIjx0aW1lb3V0PiIsIDApOw0KDQpp
ZihiaW5kZXggPCAwKSB7DQoNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigic3VjY2Vzc0ZsYWci
LCBzdWNjZXNzRmxhZyk7DQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoImVycm9yIiwgIlRoZSA8
dGltZW91dD4gdGFnIGlzIG1pc3NpbmcgZnJvbSB0aGUgaHR0cCBwcm9maWxlLiIpOw0KDQoJcmV0
dXJuOw0KDQp9DQoNCmVpbmRleCA9IGZ0cHN0cmluZy5pbmRleE9mKCI8L3RpbWVvdXQ+IiwgMCk7
DQoNCmlmKGVpbmRleCA8IDApIHsNCg0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNz
RmxhZyIsIHN1Y2Nlc3NGbGFnKTsNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZXJyb3IiLCAi
VGhlIDwvdGltZW91dD4gdGFnIGlzIG1pc3NpbmcgZnJvbSBiZWdpbmluZyBvZiB0aGUgaHR0cCBw
cm9maWxlLiIpOw0KDQoJcmV0dXJuOw0KDQp9DQoNCmlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJ0
aW1lb3V0IiwgZnRwc3RyaW5nLnN1YnN0cmluZyhiaW5kZXgrOSxlaW5kZXgpKTsNCg0KDQpiaW5k
ZXggPSBmdHBzdHJpbmcuaW5kZXhPZigiPHVzZXJuYW1lPiIsIDApOw0KDQppZihiaW5kZXggPCAw
KSB7DQoNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigic3VjY2Vzc0ZsYWciLCBzdWNjZXNzRmxh
Zyk7DQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoImVycm9yIiwgIlRoZSA8dXNlcm5hbWU+IHRh
ZyBpcyBtaXNzaW5nIGZyb20gdGhlIGh0dHAgcHJvZmlsZS4iKTsNCg0KCXJldHVybjsNCg0KfQ0K
DQplaW5kZXggPSBmdHBzdHJpbmcuaW5kZXhPZigiPC91c2VybmFtZT4iLCAwKTsNCg0KaWYoZWlu
ZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3Vj
Y2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJlcnJvciIsICJUaGUgPC91c2Vy
bmFtZT4gdGFnIGlzIG1pc3NpbmcgZnJvbSBiZWdpbmluZyBvZiB0aGUgaHR0cCBwcm9maWxlLiIp
Ow0KDQoJcmV0dXJuOw0KDQp9DQoNCmlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJ1c2VybmFtZSIs
IGZ0cHN0cmluZy5zdWJzdHJpbmcoYmluZGV4KzEwLGVpbmRleCkpOw0KDQoNCmJpbmRleCA9IGZ0
cHN0cmluZy5pbmRleE9mKCI8cGFzc3dvcmQ+IiwgMCk7DQoNCmlmKGJpbmRleCA8IDApIHsNCg0K
CWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIsIHN1Y2Nlc3NGbGFnKTsNCglp
ZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZXJyb3IiLCAiVGhlIDxwYXNzd29yZD4gdGFnIGlzIG1p
c3NpbmcgZnJvbSB0aGUgaHR0cCBwcm9maWxlLiIpOw0KDQoJcmV0dXJuOw0KDQp9DQoNCmVpbmRl
eCA9IGZ0cHN0cmluZy5pbmRleE9mKCI8L3Bhc3N3b3JkPiIsIDApOw0KDQppZihlaW5kZXggPCAw
KSB7DQoNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigic3VjY2Vzc0ZsYWciLCBzdWNjZXNzRmxh
Zyk7DQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoImVycm9yIiwgIlRoZSA8L3Bhc3N3b3JkPiB0
YWcgaXMgbWlzc2luZyBmcm9tIGJlZ2luaW5nIG9mIHRoZSBodHRwIHByb2ZpbGUuIik7DQoNCgly
ZXR1cm47DQoNCn0NCg0KaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInBhc3N3b3JkIiwgZnRwc3Ry
aW5nLnN1YnN0cmluZyhiaW5kZXgrMTAsZWluZGV4KSk7DQoNCmJpbmRleCA9IGZ0cHN0cmluZy5p
bmRleE9mKCI8cGF0aD4iLCAwKTsNCg0KaWYoYmluZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxpbmUu
aW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmlu
c2VydEFmdGVyKCJlcnJvciIsICJUaGUgPHBhdGg+IHRhZyBpcyBtaXNzaW5nIGZyb20gdGhlIGh0
dHAgcHJvZmlsZS4iKTsNCg0KCXJldHVybjsNCg0KfQ0KDQplaW5kZXggPSBmdHBzdHJpbmcuaW5k
ZXhPZigiPC9wYXRoPiIsIDApOw0KDQppZihlaW5kZXggPCAwKSB7DQoNCglpZGNQaXBlbGluZS5p
bnNlcnRBZnRlcigic3VjY2Vzc0ZsYWciLCBzdWNjZXNzRmxhZyk7DQoJaWRjUGlwZWxpbmUuaW5z
ZXJ0QWZ0ZXIoImVycm9yIiwgIlRoZSA8L3BhdGg+IHRhZyBpcyBtaXNzaW5nIGZyb20gYmVnaW5p
bmcgb2YgdGhlIGh0dHAgcHJvZmlsZS4iKTsNCg0KCXJldHVybjsNCg0KfQ0KDQppZGNQaXBlbGlu
ZS5pbnNlcnRBZnRlcigicGF0aCIsIGZ0cHN0cmluZy5zdWJzdHJpbmcoYmluZGV4KzYsZWluZGV4
KSk7DQoNCmJpbmRleCA9IGZ0cHN0cmluZy5pbmRleE9mKCI8ZmlsZW5hbWU+IiwgMCk7DQoNCmlm
KGJpbmRleCA8IDApIHsNCg0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIs
IHN1Y2Nlc3NGbGFnKTsNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZXJyb3IiLCAiVGhlIDxm
aWxlbmFtZT4gdGFnIGlzIG1pc3NpbmcgZnJvbSB0aGUgaHR0cCBwcm9maWxlLiIpOw0KCXJldHVy
bjsNCg0KfQ0KDQplaW5kZXggPSBmdHBzdHJpbmcuaW5kZXhPZigiPC9maWxlbmFtZT4iLCAwKTsN
Cg0KaWYoZWluZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NG
bGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJlcnJvciIsICJU
aGUgPC9maWxlbmFtZT4gdGFnIGlzIG1pc3NpbmcgZnJvbSBiZWdpbmluZyBvZiB0aGUgaHR0cCBw
cm9maWxlLiIpOw0KDQoJcmV0dXJuOw0KDQp9DQoNCmlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJm
aWxlbmFtZSIsIGZ0cHN0cmluZy5zdWJzdHJpbmcoYmluZGV4KzEwLGVpbmRleCkpOw0KDQpzdWNj
ZXNzRmxhZyA9ICJ0cnVlIjsNCg0KaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFn
Iiwgc3VjY2Vzc0ZsYWcpOw0KDQp9Ly9lbmQgb2YgdHJ5IGJsb2NrDQoNCmNhdGNoIChFeGNlcHRp
b24gZSkgDQp7DQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS5nZXRNZXNzYWdlKCkpOw0K
fQ0KDQpmaW5hbGx5DQp7DQppZihpZGNQaXBlbGluZSAhPSBudWxsICkgDQppZGNQaXBlbGluZS5k
ZXN0cm95KCk7DQp9DQo=</value>
</Values>
