<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listFilesInDirectory</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required targetDirectory</value>
    <value>[o] field:1:optional filenameList</value>
    <value>[o] field:0:required successFlag</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9kZWZpbmUgaW5wdXQgdmFyaWFibGVzDQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IG51bGw7
DQp0cnkNCnsNCglTdHJpbmcgc3VjY2Vzc0ZsYWcgPSAiZmFsc2UiOw0KCVN0cmluZyB0YXJnZXRE
aXJlY3RvcnkgPSBudWxsOw0KDQoJaWRjUGlwZWxpbmUgID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
DQoNCgkvLyBDaGVjayB0byBzZWUgaWYgdGhlIHRhcmdldERpcmVjdG9yeSBvYmplY3QgaXMgaW4g
dGhlIHBpcGVsaW5lDQoJaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJ0YXJnZXREaXJlY3RvcnkiKSkg
ew0KCQkvL2dldCB0aGUgdGFyZ2V0RGlyZWN0b3J5IG91dCBvZiB0aGUgcGlwZWxpbmUNCgkJdGFy
Z2V0RGlyZWN0b3J5ID0gKFN0cmluZylpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOw0KCX0gZWxzZSB7
ICAJCQkvL2lmIGl0IGlzIG5vdCBpbiB0aGUgcGlwZWxpbmUsIHRoZW4gaGFuZGxlIHRoZSBlcnJv
cg0KCQlzdWNjZXNzRmxhZyA9ICJmYWxzZSI7DQoJCQ0KCQkvL2luc2VydCB0aGUgc3VjY2Vzc0Zs
YWcgaW50byB0aGUgcGlwZWxpbmUNCgkJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NG
bGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCQkNCgkJcmV0dXJuOw0KCX0NCg0KCVN0cmluZyBmaWxlbmFt
ZVBhdHRlcm4gPSBudWxsOw0KDQoJLy8gQ2hlY2sgdG8gc2VlIGlmIHRoZSBmaWxlbmFtZVBhdHRl
cm4gb2JqZWN0IGlzIGluIHRoZSBwaXBlbGluZQ0KCWlmIChpZGNQaXBlbGluZS5maXJzdCgiZmls
ZW5hbWVQYXR0ZXJuIikpICB7DQoJCS8vZ2V0IHRoZSBmaWxlbmFtZVBhdHRlcm4gb3V0IG9mIHRo
ZSBwaXBlbGluZQ0KCQlmaWxlbmFtZVBhdHRlcm4gPSAoU3RyaW5nKWlkY1BpcGVsaW5lLmdldFZh
bHVlKCk7DQoJfQ0KCUZpbGUgdGFyZ2V0RGlyZWN0b3J5UGF0aCA9IG5ldyBGaWxlKHRhcmdldERp
cmVjdG9yeSk7DQoJDQoJaWYoIXRhcmdldERpcmVjdG9yeVBhdGguaXNEaXJlY3RvcnkoKQ0KCQl8
fCF0YXJnZXREaXJlY3RvcnlQYXRoLmV4aXN0cygpKSB7DQoNCgkJc3VjY2Vzc0ZsYWcgPSAiZmFs
c2UiOw0KDQoJCS8vaW5zZXJ0IHRoZSBzdWNjZXNzRmxhZyBpbnRvIHRoZSBwaXBlbGluZQ0KCQlp
ZGNQaXBlbGluZS5pbnNlcnRBZnRlcigic3VjY2Vzc0ZsYWciLCBzdWNjZXNzRmxhZyk7DQoJCXJl
dHVybjsNCgl9DQoNCglpZGNQaXBlbGluZS5sYXN0KCk7DQoNCglTdHJpbmdbXSBmaWxlbmFtZUxp
c3Q7DQoNCgkvL0xvYWQgdGhlIGRpcmVjb3RvcnkgbGlzdGluZw0KCWZpbGVuYW1lTGlzdCA9IHRh
cmdldERpcmVjdG9yeVBhdGgubGlzdCgpOw0KCXN1Y2Nlc3NGbGFnID0gInRydWUiOw0KDQoJLy9D
aGVjayB0byBzZWUgaWYgZGlyZWN0b3J5IGVtcHR5DQoJaWYgKChmaWxlbmFtZUxpc3Q9PW51bGwp
IHx8IChmaWxlbmFtZUxpc3QubGVuZ3RoPD0wKSkgew0KCQlmaWxlbmFtZUxpc3QgPSBudWxsOw0K
CQlzdWNjZXNzRmxhZyA9ICJ0cnVlIjsNCgl9DQoNCgkvL2luc2VydCB0aGUgZmlsZW5hbWVMaXN0
IGludG8gdGhlIHBpcGVsaW5lDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoImZpbGVuYW1lTGlz
dCIsIGZpbGVuYW1lTGlzdCk7DQoNCgkvL2luc2VydCB0aGUgc3VjY2Vzc0ZsYWcgaW50byB0aGUg
cGlwZWxpbmUNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigic3VjY2Vzc0ZsYWciLCBzdWNjZXNz
RmxhZyk7DQoNCn0vL2VuZCB0cnkNCmNhdGNoIChqYXZhLmxhbmcuRXhjZXB0aW9uIGUpDQp7DQoJ
dGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS5nZXRNZXNzYWdlKCkpOw0KfSBmaW5hbGx5IHsN
CgkvL0Fsd2F5cyBkZXN0cm95IGN1cnNvcnMgdGhhdCB5b3UgY3JlYXRlZA0KCWlmKGlkY1BpcGVs
aW5lICE9IG51bGwgKSAJDQoJCWlkY1BpcGVsaW5lLmRlc3Ryb3koKTsNCn0JDQoJDQo=</value>
</Values>
