<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">DecodeFromESDoc</value>
  <array name="sig" type="value" depth="1">
    <value>[o] record:0:required decodedDocument</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmluZyBr
ZXlWYWx1ZSA9ICIiOw0KSURhdGFCaW5Db2RlciBpZGF0YWJpbmNvZGVyID0gbnVsbDsNCklEYXRh
IGlkYXRhID0gbnVsbDsNCmJ5dGUgYWJ5dGUwW10gPSBudWxsOw0KYm9vbGVhbiBnb3RmaXJzdCA9
IGZhbHNlOw0KU3RyaW5nIGxhc3RrZXkgPSAiIjsNCg0KdHJ5ew0KaWRjUGlwZWxpbmUgPSBwaXBl
bGluZS5nZXRDdXJzb3IoKTsNCmlkY1BpcGVsaW5lLmxhc3QoKTsNCmxhc3RrZXkgPSBpZGNQaXBl
bGluZS5nZXRLZXkoKTsNCmlkYXRhYmluY29kZXIgPSBuZXcgSURhdGFCaW5Db2RlcigpOw0KDQpp
ZiAoaWRjUGlwZWxpbmUuZmlyc3QoKSl7DQoJd2hpbGUgKCFnb3RmaXJzdCAmJiAha2V5VmFsdWUu
ZXF1YWxzSWdub3JlQ2FzZShsYXN0a2V5KSkgew0KCQlrZXlWYWx1ZSA9IAlpZGNQaXBlbGluZS5n
ZXRLZXkoKTsNCgkJaWYgKChpZGNQaXBlbGluZS5nZXRLZXkoKSkuaW5kZXhPZigiUHVibGlzaGFi
bGUiKT4wKSB7DQoJCQlpZGF0YSA9IChJRGF0YSlpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOw0KCQkJ
SURhdGFDdXJzb3IgaWRDdXJzb3IgPSBpZGF0YS5nZXRDdXJzb3IoKTsNCgkJCWlmIChpZEN1cnNv
ci5maXJzdCgiSURBVEEiKSl7DQoJCQkJYWJ5dGUwID0gKGJ5dGUgW10pIGlkQ3Vyc29yLmdldFZh
bHVlKCk7DQoJCQkJaWRhdGEgPSBpZGF0YWJpbmNvZGVyLmRlY29kZUZyb21CeXRlcyhhYnl0ZTAp
Ow0KCQkJCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJkZWNvZGVkRG9jdW1lbnQiLGlkYXRhKTsN
CgkJCQlnb3RmaXJzdCA9IHRydWU7DQoJCQl9DQoJCQllbHNlIHsNCgkJCQlnb3RmaXJzdCA9IHRy
dWU7DQoJCQkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkludmFsaWQgRVMgZG9jdW1lbnQg
VHlwZSBtdXN0IGNvbnRhaW4gYW4gSURBVEEgZWxlbWVudCIpOw0KCQkJfQ0KCQl9DQoJaWRjUGlw
ZWxpbmUubmV4dCgpOw0KCX0NCglpZiAoIWdvdGZpcnN0KQ0KCQl0aHJvdyBuZXcgU2VydmljZUV4
Y2VwdGlvbigiUGlwZWxpbmUgZG9lcyBub3QgY29udGFpbiByZXF1aXJlZCBwdWJsaXNoYWJsZSBk
b2N1bWVudCIpOw0KCX0NCn0gY2F0Y2ggKGphdmEubGFuZy5FeGNlcHRpb24gZSkgew0KCXRocm93
IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOw0KfSBmaW5hbGx5IHsNCglpZihpZGNQaXBlbGluZSAh
PSBudWxsICkgeyANCgkJaWRjUGlwZWxpbmUuZGVzdHJveSgpOw0KCX0NCn0NCg==</value>
</Values>
