<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">writeFileWriter</value>
  <array name="sig" type="value" depth="1">
    <value>[i] object:0:required fileWriter</value>
    <value>[i] field:0:required fileContent</value>
    <value>[o] object:0:required fileWriter</value>
    <value>[o] field:0:required successFlag</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9kZWZpbmUgaW5wdXQgdmFyaWFibGVzIA0KSURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBudWxs
Ow0KU3RyaW5nIHN1Y2Nlc3NGbGFnID0gbnVsbDsNCg0KdHJ5DQp7DQoJU3RyaW5nIAlzdHJGaWxl
Q29udGVudCA9IG51bGw7DQoNCgkvL091dHB1dCBWYXJpYWJsZXMgDQoJQnVmZmVyZWRXcml0ZXIg
ZmlsZVdyaXRlciA9IG51bGw7DQoJDQoJaWRjUGlwZWxpbmUgID0gcGlwZWxpbmUuZ2V0Q3Vyc29y
KCk7DQoJc3VjY2Vzc0ZsYWcgPSAiZmFsc2UiOw0KDQoJLy8gQ2hlY2sgdG8gc2VlIGlmIHRoZSBm
aWxlV3JpdGVyIG9iamVjdCBpcyBpbiB0aGUgcGlwZWxpbmUNCglpZiAoaWRjUGlwZWxpbmUuZmly
c3QoImZpbGVXcml0ZXIiKSkNCgl7CQ0KCQkvL2dldCB0aGUgQnVmZmVyZWRXcml0ZXIgc3RyZWFt
IG91dCBvZiB0aGUgcGlwZWxpbmUJDQoJCWZpbGVXcml0ZXIgPSAoQnVmZmVyZWRXcml0ZXIpIGlk
Y1BpcGVsaW5lLmdldFZhbHVlKCk7DQoJfQ0KCS8vaWYgaXQgaXMgbm90IGluIHRoZSBwaXBlbGlu
ZSwgdGhlbiBoYW5kbGUgdGhlIGVycm9yDQoJZWxzZQ0KCXsNCgkJcmV0dXJuOw0KCX0NCg0KDQoJ
Ly8gQ2hlY2sgdG8gc2VlIGlmIHRoZSBmaWxlQ29udGVudCBvYmplY3QgaXMgaW4gdGhlIHBpcGVs
aW5lDQoJaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJmaWxlQ29udGVudCIpKQkNCgl7DQoJDQoJCS8v
Z2V0IHRoZSBmaWxlQ29udGVudCBvdXQgb2YgdGhlIHBpcGVsaW5lCQ0KCQlzdHJGaWxlQ29udGVu
dCA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7DQoJfQ0KCS8vaWYgaXQgaXMgbm90
IGluIHRoZSBwaXBlbGluZSwgdGhlbiBoYW5kbGUgdGhlIGVycm9yDQoJZWxzZQ0KCXsNCgkJcmV0
dXJuOw0KCX0NCgkNCglmaWxlV3JpdGVyLndyaXRlKHN0ckZpbGVDb250ZW50KTsNCg0KCS8vU2V0
IHRoZSBzdWNjZXNzIGZsYWcgYmVjYXVzZSB0aGUgc2VydmljZSB3YXMgc3VjY2Vzc2Z1bA0KCXN1
Y2Nlc3NGbGFnID0gInRydWUiOw0KDQp9DQpjYXRjaCAoRXhjZXB0aW9uIGUpIHsNCgkvL1NldCB0
aGUgc3VjY2VzcyBmbGFnIGJlY2F1c2UgdGhlIHNlcnZpY2UgZmFpbGVkDQoJc3VjY2Vzc0ZsYWcg
PSAiZmFsc2UiOw0KDQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS5nZXRNZXNzYWdlKCkp
Ow0KDQp9IGZpbmFsbHkgew0KDQoJLy9yZW1vdmUgYW55IG90aGVyIHN1Y2Nlc3NGbGFncyBmcm9t
IHBpcGxpbmUNCglpZihpZGNQaXBlbGluZS5maXJzdCgic3VjY2Vzc0ZsYWciKSkNCgl7DQoJCWlk
Y1BpcGVsaW5lLmRlbGV0ZSgpOw0KCX0NCg0KCS8vaW5zZXJ0IHRoZSBzdWNjZXNzRmxhZyBpbnRv
IHRoZSBwaXBlbGluZQ0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIsIHN1
Y2Nlc3NGbGFnKTsJDQoNCgkvL0Fsd2F5cyBkZXN0cm95IGN1cnN1cnMgdGhhdCB5b3UgY3JlYXRl
ZA0KCWlmKGlkY1BpcGVsaW5lICE9IG51bGwgKSANCgkJaWRjUGlwZWxpbmUuZGVzdHJveSgpOwkN
Cn0NCg0K</value>
</Values>
