<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">closeFileWriter</value>
  <array name="sig" type="value" depth="1">
    <value>[i] object:0:required fileWriter</value>
    <value>[o] field:0:required successFlag</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9kZWZpbmUgaW5wdXQgdmFyaWFibGVzIA0KDQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IG51
bGw7DQpTdHJpbmcgc3VjY2Vzc0ZsYWcgPSAiZmFsc2UiOw0KDQp0cnkNCnsJDQoJQnVmZmVyZWRX
cml0ZXIgZmlsZVdyaXRlciA9IG51bGw7DQoNCgkvL091dHB1dCBWYXJpYWJsZXMgDQoJaWRjUGlw
ZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCgkNCgkvLyBDaGVjayB0byBzZWUgaWYgdGhl
IGZpbGVXcml0ZXIgb2JqZWN0IGlzIGluIHRoZSBwaXBlbGluZQ0KCWlmIChpZGNQaXBlbGluZS5m
aXJzdCgiZmlsZVdyaXRlciIpKQ0KCXsJDQoJCS8vZ2V0IHRoZSBCdWZmZXJlZFdyaXRlciBzdHJl
YW0gb3V0IG9mIHRoZSBwaXBlbGluZQkJCQkJDQoJCWZpbGVXcml0ZXIgPSAoQnVmZmVyZWRXcml0
ZXIpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7DQoJfQ0KCS8vaWYgaXQgaXMgbm90IGluIHRoZSBw
aXBlbGluZSwgdGhlbiBoYW5kbGUgdGhlIGVycm9yDQoJZWxzZQ0KCXsNCgkJc3VjY2Vzc0ZsYWcg
PSAiZmFsc2UiOwkNCg0KCQkvL2luc2VydCB0aGUgc3VjY2Vzc0ZsYWcgaW50byB0aGUgcGlwZWxp
bmUNCgkJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcp
Ow0KCQlyZXR1cm47DQoJfQ0KDQoJLy8gVHJ5IHRvIGZsdXNoIHRoZSBmaWxlV3JpdGVyIG9iamVj
dC4gIEhhbmRsZSB0aGUgZXhjZXB0aW9uIGlmIGl0IGZhaWxzLg0KCQ0KCWlmKGZpbGVXcml0ZXIg
IT0gbnVsbCkgDQoJCWZpbGVXcml0ZXIuY2xvc2UoKTsNCglzdWNjZXNzRmxhZyA9ICJ0cnVlIjsJ
CQkJCQkNCgkNCg0KfS8vZW5kIG9mIHRyeQ0KDQoNCmNhdGNoIChqYXZhLmxhbmcuRXhjZXB0aW9u
IGUpDQp7DQoJLy9TZXQgdGhlIHN1Y2Nlc3MgZmxhZyBiZWNhdXNlIHRoZSBzZXJ2aWNlIGZhaWxl
ZA0KCXN1Y2Nlc3NGbGFnID0gImZhbHNlIjsNCgkNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlv
bihlLmdldE1lc3NhZ2UoKSk7DQp9IGZpbmFsbHkgew0KDQoJLy9yZW1vdmUgYW55IG90aGVyIHN1
Y2Nlc3NGbGFncyBmcm9tIHBpcGxpbmUNCglpZihpZGNQaXBlbGluZS5maXJzdCgic3VjY2Vzc0Zs
YWciKSkNCgl7DQoJCWlkY1BpcGVsaW5lLmRlbGV0ZSgpOw0KCX0NCg0KCS8vaW5zZXJ0IHRoZSBz
dWNjZXNzRmxhZyBpbnRvIHRoZSBwaXBlbGluZQ0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJz
dWNjZXNzRmxhZyIsIHN1Y2Nlc3NGbGFnKTsNCgkNCgkvL0Fsd2F5cyBkZXN0cm95IGN1cnNvcnMg
dGhhdCB5b3UgY3JlYXRlZA0KCWlmKGlkY1BpcGVsaW5lICE9IG51bGwgKSAJDQoJICAgIGlkY1Bp
cGVsaW5lLmRlc3Ryb3koKTsNCn0JDQo=</value>
</Values>
