<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">checkPattern</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required actualFilePattern</value>
    <value>[i] field:0:required testFilePattern</value>
    <value>[o] field:0:required pattern</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gR2V0IElEYXRhQ3Vyc29yIHRvIG1hbmlwdWxhdGUgcGlwZWxpbmUNCklEYXRhQ3Vyc29yIGlk
Y1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNClN0cmluZyBhY3R1YWxGaWxlUGF0
dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoaWRjUGlwZWxpbmUsICJhY3R1YWxGaWxlUGF0dGVy
biIpOw0KU3RyaW5nIHRlc3RGaWxlUGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoaWRjUGlw
ZWxpbmUsICJ0ZXN0RmlsZVBhdHRlcm4iKTsNClN0cmluZyBhY3R1YWxGaWxlUGF0aCA9IG5ldyBT
dHJpbmcoKTsNClN0cmluZyBhY3R1YWxGaWxlTmFtZSA9IG5ldyBTdHJpbmcoKTsNClN0cmluZyB0
ZXN0RmlsZU5hbWUgPSBuZXcgU3RyaW5nKCk7DQpTdHJpbmcgdGVzdEZpbGVQYXRoID0gbmV3IFN0
cmluZygpOw0KaW50IHBhdHRlcm4gPSAtMTsNCg0KLy9pZiBmdHAgY3JpdGVyaWEgaW5jbHVkZXMg
YSBzcGVjaWZpYyBwYXRoDQppZih0ZXN0RmlsZVBhdHRlcm4uY29udGFpbnMoIi8iKSl7DQoNCmFj
dHVhbEZpbGVQYXRoID0gYWN0dWFsRmlsZVBhdHRlcm4uc3Vic3RyaW5nKDAsIGFjdHVhbEZpbGVQ
YXR0ZXJuLmxhc3RJbmRleE9mKCIvIikpOw0KYWN0dWFsRmlsZU5hbWUgPSBhY3R1YWxGaWxlUGF0
dGVybi5zdWJzdHJpbmcoYWN0dWFsRmlsZVBhdHRlcm4ubGFzdEluZGV4T2YoIi8iKSxhY3R1YWxG
aWxlUGF0dGVybi5sZW5ndGgoKSk7DQp0ZXN0RmlsZVBhdGggPSB0ZXN0RmlsZVBhdHRlcm4uc3Vi
c3RyaW5nKDAsIHRlc3RGaWxlUGF0dGVybi5sYXN0SW5kZXhPZigiLyIpKTsNCnRlc3RGaWxlTmFt
ZSA9IHRlc3RGaWxlUGF0dGVybi5zdWJzdHJpbmcodGVzdEZpbGVQYXR0ZXJuLmxhc3RJbmRleE9m
KCIvIiksdGVzdEZpbGVQYXR0ZXJuLmxlbmd0aCgpKTsNCnRlc3RGaWxlTmFtZSA9IHRlc3RGaWxl
TmFtZS5yZXBsYWNlKCIqIiwgIiIpOw0KdGVzdEZpbGVOYW1lID0gdGVzdEZpbGVOYW1lLnJlcGxh
Y2UoIi8iLCAiIik7DQoNCmlmKGFjdHVhbEZpbGVQYXRoLmVxdWFscyh0ZXN0RmlsZVBhdGgpICYm
IGFjdHVhbEZpbGVOYW1lLmNvbnRhaW5zKHRlc3RGaWxlTmFtZSkpIHBhdHRlcm4gPSAxOw0KZWxz
ZSBpZihhY3R1YWxGaWxlUGF0aC5lcXVhbHModGVzdEZpbGVQYXRoKSAmJiBhY3R1YWxGaWxlUGF0
dGVybi5jb250YWlucyh0ZXN0RmlsZVBhdHRlcm4pKSBwYXR0ZXJuID0gMTsNCmVsc2UgaWYoYWN0
dWFsRmlsZVBhdGguZXF1YWxzKHRlc3RGaWxlUGF0aCkgJiYgdGVzdEZpbGVOYW1lLmVxdWFscygi
LiIpKSBwYXR0ZXJuID0gMTsNCg0KfQ0KDQpJRGF0YVV0aWwucHV0KCBpZGNQaXBlbGluZSwgImFj
dHVhbEZpbGVQYXRoIiwgYWN0dWFsRmlsZVBhdGgpOw0KSURhdGFVdGlsLnB1dCggaWRjUGlwZWxp
bmUsICJhY3R1YWxGaWxlTmFtZSIsIGFjdHVhbEZpbGVOYW1lKTsNCklEYXRhVXRpbC5wdXQoIGlk
Y1BpcGVsaW5lLCAidGVzdEZpbGVQYXRoIiwgdGVzdEZpbGVQYXRoKTsNCklEYXRhVXRpbC5wdXQo
IGlkY1BpcGVsaW5lLCAidGVzdEZpbGVOYW1lIiwgdGVzdEZpbGVOYW1lKTsNCklEYXRhVXRpbC5w
dXQoIGlkY1BpcGVsaW5lLCAicGF0dGVybiIsIHBhdHRlcm4pOw0K</value>
</Values>
