<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getSystemProperties</value>
  <array name="sig" type="value" depth="1">
    <value>[o] field:2:required propertyList</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqIFNlcnZpY2UgaXMgZGVzaWduZWQgdG8gcmV0dXJuIGEgbGlzdCBvZiBhbGwgYXZhaWxhYmxl
IHN5c3RlbSBwcm9wZXJ0aWVzLg0KICAqDQogICogQGF1dGhvciBSeWFuIEpvaG5zdG9uLCBQcm9m
ZXNzaW9uYWwgU2VydmljZXMsIHdlYk1ldGhvZHMsIEluYy4NCiAgKiBAdmVyc2lvbiAxLjENCiAg
KiBNb2RpZmllZCBzbGlnaHRseSB0byByZXBsYWNlIElEYXRhSGFzaEN1cnNvciB3aXRoIElEYXRh
Q3Vyc29yIChFcmljKQ0KICAqIE1vZGlmaWVkIHRvIGNoZWNrIGZvciBleGlzdGluZyBvZiBwcm9w
ZXJ0eUxpc3QgYmVmb3JlIGRlbGV0ZSAoUm9uYWxkIEIpDQogICovDQoNCklEYXRhQ3Vyc29yIGlk
YyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KUHJvcGVydGllcyBwcm9wID0gU3lzdGVtLmdldFBy
b3BlcnRpZXMoKTsNCkVudW1lcmF0aW9uIHByb3BLZXlMaXN0ID0gcHJvcC5wcm9wZXJ0eU5hbWVz
KCk7DQpWZWN0b3IgcHJvcFZlYyA9IG5ldyBWZWN0b3IoKTsNClZlY3RvciB2YWx1ZVZlYyA9IG5l
dyBWZWN0b3IoKTsNCg0Kb3V0ZXI6d2hpbGUodHJ1ZSkNCnsNCglpZihwcm9wS2V5TGlzdC5oYXNN
b3JlRWxlbWVudHMoKSA9PSB0cnVlKQ0Kew0KCQlTdHJpbmcgZWxlbWVudE5hbWUgPSAoU3RyaW5n
KXByb3BLZXlMaXN0Lm5leHRFbGVtZW50KCk7DQoJCVN0cmluZyBlbGVtZW50VmFsdWUgPSBTeXN0
ZW0uZ2V0UHJvcGVydHkoZWxlbWVudE5hbWUsICJObyBwcm9wZXJ0eSBmb3VuZCIpOw0KCQlwcm9w
VmVjLmFkZEVsZW1lbnQoIGVsZW1lbnROYW1lICk7DQoJCXZhbHVlVmVjLmFkZEVsZW1lbnQoIGVs
ZW1lbnRWYWx1ZSApOw0KCX0NCgllbHNlDQoJCWJyZWFrIG91dGVyOw0KfQ0KDQpTdHJpbmdbXSBh
bGxQcm9wc0NvbEhlYWRlcnMgPSB7IktleSIsIlZhbHVlIn07DQpUYWJsZSBhbGxQcm9wcyA9IG5l
dyBUYWJsZShhbGxQcm9wc0NvbEhlYWRlcnMpOw0KZm9yKGludCBpPTA7aTxwcm9wVmVjLnNpemUo
KTtpKyspDQp7DQoJU3RyaW5nW10gaW5kaXZpZHVhbFJvd3MgPSB7IChTdHJpbmcpcHJvcFZlYy5l
bGVtZW50QXQoaSksKFN0cmluZyl2YWx1ZVZlYy5lbGVtZW50QXQoaSkgfTsNCglhbGxQcm9wcy5h
ZGRSb3coaW5kaXZpZHVhbFJvd3MpOw0KfQ0KDQppZiAoaWRjLmZpcnN0KCJwcm9wZXJ0eUxpc3Qi
KSkNCglpZGMuZGVsZXRlKCk7DQoNCmlkYy5pbnNlcnRBZnRlcigicHJvcGVydHlMaXN0IiwgYWxs
UHJvcHMpOw0KaWRjLmRlc3Ryb3koKTsNCg==</value>
</Values>
