<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">deleteFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[i] field:0:required directory</value>
    <value>[o] field:0:required successFlag</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9kZWZpbmUgaW5wdXQgdmFyaWFibGVzDQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IG51bGw7
IA0KU3RyaW5nIGxvbmdGaWxlbmFtZSwgZmlsZW5hbWUsIGRpcmVjdG9yeTsNClN0cmluZyBzdWNj
ZXNzRmxhZyA9IG51bGw7DQp0cnkgew0KCS8vT3V0cHV0IFZhcmlhYmxlcw0KCXN1Y2Nlc3NGbGFn
PSAiZmFsc2UiOw0KDQoJaWRjUGlwZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCg0KCS8v
IENoZWNrIHRvIHNlZSBpZiB0aGUgZmlsZW5hbWUgb2JqZWN0IGlzIGluIHRoZSBwaXBlbGluZQ0K
CWlmIChpZGNQaXBlbGluZS5maXJzdCgiZmlsZW5hbWUiKSkgew0KDQoJCS8vZ2V0IHRoZSBmaWxl
bmFtZSBzdHJpbmcgb2JqZWN0IG91dCBvZiB0aGUgcGlwZWxpbmUNCgkJZmlsZW5hbWUgPSAoU3Ry
aW5nKWlkY1BpcGVsaW5lLmdldFZhbHVlKCk7DQoJfQ0KCS8vaWYgaXQgaXMgbm90IGluIHRoZSBw
aXBlbGluZSwgdGhlbiBoYW5kbGUgdGhlIGVycm9yDQoJZWxzZSB7DQoJCXN1Y2Nlc3NGbGFnID0g
ImZhbHNlIjsNCgkJcmV0dXJuOw0KCX0NCg0KDQoJLy8gQ2hlY2sgdG8gc2VlIGlmIHRoZSBkaXJl
Y3Rvcnkgb2JqZWN0IGlzIGluIHRoZSBwaXBlbGluZQ0KCWlmIChpZGNQaXBlbGluZS5maXJzdCgi
ZGlyZWN0b3J5IikpIHsNCgkJLy9nZXQgdGhlIGRpcmVjdG9yeSBzdHJpbmcgb2JqZWN0IG91dCBv
ZiB0aGUgcGlwZWxpbmUNCgkJZGlyZWN0b3J5ID0gKFN0cmluZylpZGNQaXBlbGluZS5nZXRWYWx1
ZSgpOw0KCX0NCgkvL2lmIGl0IGlzIG5vdCBpbiB0aGUgcGlwZWxpbmUsIHRoZW4gaGFuZGxlIHRo
ZSBlcnJvcg0KCWVsc2Ugew0KCQlzdWNjZXNzRmxhZyA9ICJmYWxzZSI7DQoJCXJldHVybjsNCgl9
DQoNCgkvL0NoZWNrIGlmIGEgZGlyZWN0b3J5IHdhcyBlbnRlcmVkDQoJaWYgKGRpcmVjdG9yeT09
bnVsbCkgew0KCQlsb25nRmlsZW5hbWUgPSAoZmlsZW5hbWUpOw0KCX0gZWxzZSB7DQoJCWxvbmdG
aWxlbmFtZSA9IChkaXJlY3RvcnkgKyBGaWxlLnNlcGFyYXRvciArIGZpbGVuYW1lKTsNCgl9DQoN
CgkvL0Fzc2lnbiBmdWxsIHBhdGggbmFtZSB0byBhIGZpbGUgb2JqZWN0DQoJRmlsZSBsb2NhbEZp
bGUgPSBuZXcgRmlsZShsb25nRmlsZW5hbWUpOw0KDQoJLy9UcnkgdG8gZGVsZXRlIHRoZSBmaWxl
DQoJLy9DaGVjayBpcyBhIGRpcmVjdG9yeSB3YXMgZW50ZXJlZA0KCQ0KCWlmIChsb2NhbEZpbGUu
aXNEaXJlY3RvcnkoKSkgew0KCQlzdWNjZXNzRmxhZyA9ICJmYWxzZSI7DQoJfSBlbHNlIGlmICgh
bG9jYWxGaWxlLmV4aXN0cygpKSB7IAkvL0NoZWNrIGlmIHRoZSBmaWxlIGRvZXNuJ3QgZXhpc3QN
CgkJc3VjY2Vzc0ZsYWcgPSAiZmFsc2UiOw0KCX0gZWxzZSBpZiAoIWxvY2FsRmlsZS5jYW5Xcml0
ZSgpKSB7ICAgIAkvL2NoZWNrIGlmIHlvdSBjYW4gd3JpdGUgdG8gZmlsZQ0KCQlzdWNjZXNzRmxh
ZyA9ICJmYWxzZSI7DQoJfSBlbHNlIHsgCQkJCS8vRmlsZSBjYW4gYmUgZGVsZXRlZA0KCQlsb2Nh
bEZpbGUuZGVsZXRlKCk7DQoJCXN1Y2Nlc3NGbGFnID0gInRydWUiOw0KCX0NCiAvL2luc2VydCB0
aGUgc3VjY2Vzc0ZsYWcgaW50byB0aGUgcGlwZWxpbmUNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRl
cigic3VjY2Vzc0ZsYWciLCBzdWNjZXNzRmxhZyk7DQp9DQovL0NhdGNoIGFueSBvdGhlciBlcnJv
cidzDQpjYXRjaCAoRXhjZXB0aW9uIGUpIHsNCglzdWNjZXNzRmxhZyA9ICJmYWxzZSI7DQoJaWRj
UGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCXRocm93
IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsNCn0gZmluYWxseSB7DQoNCgkv
L0Fsd2F5cyBkZXN0cm95IGN1cnNvcnMgdGhhdCB5b3UgY3JlYXRlZA0KCWlmKGlkY1BpcGVsaW5l
ICE9IG51bGwgKSANCgkJaWRjUGlwZWxpbmUuZGVzdHJveSgpOw0KDQp9DQo=</value>
</Values>
