<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getRealError</value>
  <array name="sig" type="value" depth="1">
    <value>[i] recref:0:optional lastError pub.event:exceptionInfo</value>
    <value>[o] recref:0:optional realError pub.event:exceptionInfo</value>
    <value>[o] field:0:required callStackString</value>
    <value>[o] field:0:required topLevelService</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCklEYXRh
CWxhc3RFcnJvciA9IElEYXRhVXRpbC5nZXRJRGF0YSggcGlwZWxpbmVDdXJzb3IsICJsYXN0RXJy
b3IiICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoNCg0KaWYgKGxhc3RFcnJvciAhPSBu
dWxsKQ0Kew0KCVN0cmluZ0J1ZmZlciBjYWxsU3RhY2tCdWZmZXIgPSBuZXcgU3RyaW5nQnVmZmVy
KCk7DQoJSURhdGEgcmVhbEVycm9yID0gdHJhdmVyc2VMYXN0RXJyb3IobGFzdEVycm9yLCBjYWxs
U3RhY2tCdWZmZXIpOw0KCWlmKHJlYWxFcnJvciA9PSBudWxsKQ0KCQlyZWFsRXJyb3IgPSBsYXN0
RXJyb3I7DQoNCgljb20ud20uYXBwLmIyYi5zZXJ2ZXIuSW52b2tlU3RhdGUgaXMgPSBjb20ud20u
YXBwLmIyYi5zZXJ2ZXIuSW52b2tlU3RhdGUuZ2V0Q3VycmVudFN0YXRlKCk7IA0KICAgICAgCWph
dmEudXRpbC5TdGFjayBjYWxsU3RhY2sgPSBpcy5nZXRDYWxsU3RhY2soKTsNCg0KICAgICAgICBT
dHJpbmcgYXNbXSA9IG51bGw7DQogICAgICAgIGlmKGNhbGxTdGFjayAhPSBudWxsKQ0KICAgICAg
ICB7DQogICAgICAgICAgICAJCWludCBpID0gY2FsbFN0YWNrLnNpemUoKTsNCiAgICAgICAgICAg
IAkJYXMgPSBuZXcgU3RyaW5nW2ldOw0KICAgICAgICAgICAgCQlmb3IoaW50IGogPSAwOyBqIDwg
aTsgaisrKQ0KICAgICAgICAgICAgCQl7DQogICAgICAgICAgICAgICAgCQljb20ud20ubGFuZy5u
cy5OU1NlcnZpY2UgbnNzZXJ2aWNlID0gKGNvbS53bS5sYW5nLm5zLk5TU2VydmljZSljYWxsU3Rh
Y2suZWxlbWVudEF0KGopOw0KICAgICAgICAgICAgICAgCSAJCWFzW2pdID0gbnNzZXJ2aWNlLmdl
dE5TTmFtZSgpLmdldEZ1bGxOYW1lKCk7DQoJCQkJLy9XbUxvZ1V0aWwubG9nRGVidWcxKDQsIkNh
bGwgU3RhY2sgIiArIGogKyAiIC0gIiArIGFzW2pdKTsNCiAgICAgICAgICAgIAkJfQ0KDQogICAg
ICAgIH0NCg0KCVN0cmluZyB0b3BMZXZlbFNlcnZpY2UgPSBudWxsOw0KCWlmKGFzLmxlbmd0aCA+
PSAzKQ0KCXsNCgkJdG9wTGV2ZWxTZXJ2aWNlID0gYXNbYXMubGVuZ3RoLTNdOw0KCX1lbHNlDQoJ
ew0KCQkvL1RoaXMgZXJyb3Igd2FzIGNhdXNlZCB3aGlsZSBzdGVwcGluZyB0aHJvdWdoIGZsb3cu
DQoJCUlEYXRhQ3Vyc29yIHJlYWxFcnJvckN1cnNvciA9IHJlYWxFcnJvci5nZXRDdXJzb3IoKTsN
CgkJdG9wTGV2ZWxTZXJ2aWNlID0gSURhdGFVdGlsLmdldFN0cmluZyhyZWFsRXJyb3JDdXJzb3Is
ICJzZXJ2aWNlIik7DQoJCXJlYWxFcnJvckN1cnNvci5kZXN0cm95KCk7CQkJDQoJfQ0KCQ0KCXBp
cGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoJSURhdGFVdGlsLnB1dCggcGlw
ZWxpbmVDdXJzb3IsICJyZWFsRXJyb3IiLCByZWFsRXJyb3IpOw0KCWlmKHRvcExldmVsU2Vydmlj
ZSA9PSBudWxsKQ0KCXsNCgkJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJjYWxsU3Rh
Y2tTdHJpbmciLCBjYWxsU3RhY2tCdWZmZXIudG9TdHJpbmcoKSk7DQoJfWVsc2UNCgl7DQoJCUlE
YXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAiY2FsbFN0YWNrU3RyaW5nIiwgY2FsbFN0YWNr
QnVmZmVyLnRvU3RyaW5nKCkgICsgdG9wTGV2ZWxTZXJ2aWNlICsgIlxuIik7DQoJCUlEYXRhVXRp
bC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAidG9wTGV2ZWxTZXJ2aWNlIiwgdG9wTGV2ZWxTZXJ2aWNl
KTsNCgl9DQoJcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwkNCn0NCg==</value>
</Values>
