<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">fireCommandExecWithErr</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required command</value>
    <value>[o] field:0:required output</value>
    <value>[o] field:0:required error</value>
    <value>[o] field:0:required successFlag</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CS8vZGVmaW5lIGlucHV0IHZhcmlhYmxlcyANCglJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBp
cGVsaW5lLmdldEN1cnNvcigpOw0KCVN0cmluZyAJc3RyRmlsZUNvbnRlbnQgPSBudWxsOw0KDQoJ
Ly9PdXRwdXQgVmFyaWFibGVzIA0KCVN0cmluZyBzdWNjZXNzRmxhZyA9ICJmYWxzZSI7IA0KCVN0
cmluZyBmdWxsQ29tbWFuZCA7ICAgIA0KICAgIA0KCS8vIENoZWNrIHRvIHNlZSBpZiB0aGUgZnVs
bENvbW1hbmQgb2JqZWN0IGlzIGluIHRoZSBwaXBlbGluZQ0KCWlmIChpZGNQaXBlbGluZS5maXJz
dCgiY29tbWFuZCIpKQ0KCXsJICANCgkJLy9nZXQgdGhlIGZ1bGxDb21tYW5kIHN0cmVhbSBvdXQg
b2YgdGhlIHBpcGVsaW5lCQkJCQkNCgkJZnVsbENvbW1hbmQgPSAoU3RyaW5nKSBpZGNQaXBlbGlu
ZS5nZXRWYWx1ZSgpOw0KCX0NCgkvL2lmIGl0IGlzIG5vdCBpbiB0aGUgcGlwZWxpbmUsIHRoZW4g
aGFuZGxlIHRoZSBlcnJvcg0KCWVsc2UNCgl7ICANCgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oIlJlcXVpcmVkIHBhcmFtZXRlciAnY29tbWFuZCcgbWlzc2luZyIpOwkJIAkNCgl9DQoJdHJ5
IHsNCiAJCS8vRXhlY3V0ZSB0aGUgY29tbWFuZC4gSGFuZGxlIHRoZSBleGNlcHRpb24gaWYgaXQg
ZmFpbHMuCQkNCgkJDQoJCVByb2Nlc3MgY2hpbGQgPSAgIFJ1bnRpbWUuZ2V0UnVudGltZSgpLmV4
ZWMoZnVsbENvbW1hbmQpOw0KCQkNCgkJc3VjY2Vzc0ZsYWc9InRydWUiOwkJDQoJCWludCBjdD0w
Ow0KCQlTdHJpbmcgb3V0cHV0PSIiOwkJDQoJCVN0cmluZyBlcnJvcj0iIjsJCQ0KCQkNCiAgICAg
ICAgICAgICAgICBCdWZmZXJlZFJlYWRlciBpbnB1dCA9ICBuZXcgQnVmZmVyZWRSZWFkZXIobmV3
IElucHV0U3RyZWFtUmVhZGVyKGNoaWxkLmdldEVycm9yU3RyZWFtKCkpKTsNCgkJU3RyaW5nIGxp
bmUgPSBpbnB1dC5yZWFkTGluZSgpOw0KCQkNCgkJd2hpbGUgKCgobGluZSA9IGlucHV0LnJlYWRM
aW5lKCkpICE9IG51bGwpKSB7DQogICAgICAgICAgICAgICAgICAgICAgU3lzdGVtLm91dC5wcmlu
dGxuKGxpbmUpOw0KICAgICAgICAgICAgICAgICAgICAgIGVycm9yPWVycm9yK2xpbmU7CQkJCQkJ
CQkJCQkJCQ0KCSAgICAgICAgfQ0KCQkNCiAgICAgICAgCWlucHV0ID0gIG5ldyBCdWZmZXJlZFJl
YWRlcihuZXcgSW5wdXRTdHJlYW1SZWFkZXIoY2hpbGQuZ2V0SW5wdXRTdHJlYW0oKSkpOw0KCQls
aW5lID0gbnVsbDsNCgkJbGluZSA9IGlucHV0LnJlYWRMaW5lKCk7DQogICAgICAgCSAgICAgICAg
DQoJICAgICAgICB3aGlsZSAoKChsaW5lID0gaW5wdXQucmVhZExpbmUoKSkgIT0gbnVsbCkpIHsN
CiAgICAgICAJCSAgICAgIG91dHB1dD1vdXRwdXQrbGluZTsNCgkJfQ0KDQoJCSAgDQogICAgICAg
IAlpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZXJyb3IiLCBlcnJvcik7DQoJCWlkY1BpcGVsaW5l
Lmluc2VydEFmdGVyKCJvdXRwdXQiLCBvdXRwdXQpOw0KCQkNCiAgICAgICAgCWlucHV0LmNsb3Nl
KCk7DQoJfQkgDQoJY2F0Y2ggKGphdmEubGFuZy5FeGNlcHRpb24gZXgpIA0KCXsNCiAgCSAgICAg
IHN1Y2Nlc3NGbGFnPSJGYWxzZSI7DQoJICAgICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24o
ZXgpOwkJDQogCX0NCg0KCS8vaW5zZXJ0IHRoZSBzdWNjZXNzRmxhZyBpbnRvIHRoZSBwaXBlbGlu
ZQ0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIsIHN1Y2Nlc3NGbGFnKTsJ
DQoNCgkvL0Fsd2F5cyBkZXN0cm95IGN1cnNvcnMgdGhhdCB5b3UgY3JlYXRlZA0KCWlkY1BpcGVs
aW5lLmRlc3Ryb3koKTsNCg==</value>
</Values>
