<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getSmtpServer</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBudWxsOw0KDQoNCnRyeQ0KeyANCglwaXBlbGlu
ZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KDQoJUHJvcGVydGllcyBjb25maWcgPSBT
eXN0ZW0uZ2V0UHJvcGVydGllcygpOw0KCVN0cmluZyBzdHIgPSBjb25maWcuZ2V0UHJvcGVydHko
IndhdHQuc2VydmVyLnNtdHBTZXJ2ZXIiKTsNCiAgICAgICAgU3RyaW5nIHN0clBvcnQgPSBjb25m
aWcuZ2V0UHJvcGVydHkoIndhdHQuc2VydmVyLnNtdHBTZXJ2ZXJQb3J0Iik7DQoJU3RyaW5nIGVt
YWlsID0gY29uZmlnLmdldFByb3BlcnR5KCJ3YXR0LnNlcnZlci5NYWlsQWxpYXMiKTsNCglTdHJp
bmcgY2hhcnNldCA9IGNvbmZpZy5nZXRQcm9wZXJ0eSgid2F0dC5zZXJ2ZXIuZW1haWwuY2hhcnNl
dCIpOw0KCVN0cmluZyBlbWFpbGZyb20gPSBjb25maWcuZ2V0UHJvcGVydHkoIndhdHQuc2VydmVy
LmVtYWlsZnJvbSIpOw0KDQoJDQoJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJzbXRw
U2VydmVyIiwgc3RyICk7DQogICAgICAgIElEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAi
c210cFNlcnZlclBvcnQiLCBzdHJQb3J0ICk7DQoJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJz
b3IsICJtYWlsQWxpYXMiLCBlbWFpbCApOw0KCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29y
LCJlbWFpbGZyb20iLCBlbWFpbGZyb20gKTsNCglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNv
ciwiY2hhcnNldCIsIGNoYXJzZXQgKTsNCn0NCg0KY2F0Y2goamF2YS5sYW5nLkV4Y2VwdGlvbiBl
eCkNCgl7IA0KCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihleC5nZXRNZXNzYWdlKCkpOyAN
Cgl9DQoJZmluYWxseSANCgl7IA0KCQlpZihwaXBlbGluZUN1cnNvciAhPSBudWxsICkgDQoJCQlw
aXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoJDQoJfQ0KCQ0KCQ==</value>
</Values>
