<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parseConnectionString</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required string</value>
    <value>[o] field:0:required url</value>
    <value>[o] field:0:required port</value>
    <value>[o] field:0:required password</value>
    <value>[o] field:0:required username</value>
    <value>[o] field:0:required timeout</value>
    <value>[o] field:0:required encoding</value>
    <value>[o] field:0:required error</value>
    <value>[o] field:0:required successFlag</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">U3RyaW5nIGNvbm5TdHJpbmc7DQppbnQgYmluZGV4Ow0KaW50IGVpbmRleDsNCg0KU3RyaW5nIHN1
Y2Nlc3NGbGFnID0gImZhbHNlIjsNCg0KSURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBudWxsOw0K
DQp0cnl7DQoNCmlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCmlmIChpZGNQ
aXBlbGluZS5maXJzdCgic3RyaW5nIikpIHsNCg0KCWNvbm5TdHJpbmcgPSAoU3RyaW5nKWlkY1Bp
cGVsaW5lLmdldFZhbHVlKCk7DQoNCn0NCg0KZWxzZSB7DQoNCg0KDQoJaWRjUGlwZWxpbmUuaW5z
ZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmluc2Vy
dEFmdGVyKCJlcnJvciIsICJObyBpbnB1dCBzdHJpbmcgZm9yIGNvbm5lY3Rpb24gdXJsLiIpOw0K
DQoJcmV0dXJuOw0KDQp9DQoNCg0KY29ublN0cmluZyA9IGNvbm5TdHJpbmcudHJpbSgpOw0KDQpi
aW5kZXggPSBjb25uU3RyaW5nLmluZGV4T2YoIjx1cmw+IiwgMCk7DQoNCmlmKGJpbmRleCA8IDAp
IHsNCg0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIsIHN1Y2Nlc3NGbGFn
KTsNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZXJyb3IiLCAiVGhlIDx1cmw+IHRhZyBpcyBt
aXNzaW5nIGZyb20gdGhlIGh0dHAgcHJvZmlsZS4iKTsNCg0KCXJldHVybjsNCg0KfQ0KDQplaW5k
ZXggPSBjb25uU3RyaW5nLmluZGV4T2YoIjwvdXJsPiIsIDApOw0KDQppZihlaW5kZXggPCAwKSB7
DQoNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigic3VjY2Vzc0ZsYWciLCBzdWNjZXNzRmxhZyk7
DQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoImVycm9yIiwgIlRoZSA8L3VybD4gdGFnIGlzIG1p
c3NpbmcgZnJvbSBiZWdpbmluZyBvZiB0aGUgaHR0cCBwcm9maWxlLiIpOw0KDQoJcmV0dXJuOw0K
DQp9DQoNCmlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJ1cmwiLCBjb25uU3RyaW5nLnN1YnN0cmlu
ZyhiaW5kZXgrNSxlaW5kZXgpKTsNCg0KYmluZGV4ID0gY29ublN0cmluZy5pbmRleE9mKCI8cG9y
dD4iLCAwKTsNCg0KaWYoYmluZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIo
InN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJl
cnJvciIsICJUaGUgPHBvcnQ+IHRhZyBpcyBtaXNzaW5nIGZyb20gdGhlIGh0dHAgcHJvZmlsZS4i
KTsNCg0KCXJldHVybjsNCg0KfQ0KDQplaW5kZXggPSBjb25uU3RyaW5nLmluZGV4T2YoIjwvcG9y
dD4iLCAwKTsNCg0KaWYoZWluZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIo
InN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJl
cnJvciIsICJUaGUgPC9wb3J0PiB0YWcgaXMgbWlzc2luZyBmcm9tIGJlZ2luaW5nIG9mIHRoZSBo
dHRwIHByb2ZpbGUuIik7DQoNCglyZXR1cm47DQoNCn0NCg0KaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0
ZXIoInBvcnQiLCBjb25uU3RyaW5nLnN1YnN0cmluZyhiaW5kZXgrNixlaW5kZXgpKTsNCg0KYmlu
ZGV4ID0gY29ublN0cmluZy5pbmRleE9mKCI8ZW5jb2Rpbmc+IiwgMCk7DQoNCmlmKGJpbmRleCA8
IDApIHsNCg0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIsIHN1Y2Nlc3NG
bGFnKTsNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZXJyb3IiLCAiVGhlIDxlbmNvZGluZz4g
dGFnIGlzIG1pc3NpbmcgZnJvbSB0aGUgaHR0cCBwcm9maWxlLiIpOw0KDQoJcmV0dXJuOw0KDQp9
DQoNCmVpbmRleCA9IGNvbm5TdHJpbmcuaW5kZXhPZigiPC9lbmNvZGluZz4iLCAwKTsNCg0KaWYo
ZWluZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwg
c3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJlcnJvciIsICJUaGUgPC9l
bmNvZGluZz4gdGFnIGlzIG1pc3NpbmcgZnJvbSBiZWdpbmluZyBvZiB0aGUgaHR0cCBwcm9maWxl
LiIpOw0KDQoJcmV0dXJuOw0KDQp9DQoNCg0KU3RyaW5nIGVuY29kaW5nID0gY29ublN0cmluZy5z
dWJzdHJpbmcoYmluZGV4KzEwLGVpbmRleCk7DQoNCmlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJl
bmNvZGluZyIsIGVuY29kaW5nKTsNCg0KYmluZGV4ID0gY29ublN0cmluZy5pbmRleE9mKCI8dGlt
ZW91dD4iLCAwKTsNCg0KaWYoYmluZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0
ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVy
KCJlcnJvciIsICJUaGUgPHRpbWVvdXQ+IHRhZyBpcyBtaXNzaW5nIGZyb20gdGhlIGh0dHAgcHJv
ZmlsZS4iKTsNCg0KCXJldHVybjsNCg0KfQ0KDQplaW5kZXggPSBjb25uU3RyaW5nLmluZGV4T2Yo
IjwvdGltZW91dD4iLCAwKTsNCg0KaWYoZWluZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxpbmUuaW5z
ZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmluc2Vy
dEFmdGVyKCJlcnJvciIsICJUaGUgPC90aW1lb3V0PiB0YWcgaXMgbWlzc2luZyBmcm9tIGJlZ2lu
aW5nIG9mIHRoZSBodHRwIHByb2ZpbGUuIik7DQoNCglyZXR1cm47DQoNCn0NCg0KaWRjUGlwZWxp
bmUuaW5zZXJ0QWZ0ZXIoInRpbWVvdXQiLCBjb25uU3RyaW5nLnN1YnN0cmluZyhiaW5kZXgrOSxl
aW5kZXgpKTsNCg0KDQpiaW5kZXggPSBjb25uU3RyaW5nLmluZGV4T2YoIjx1c2VybmFtZT4iLCAw
KTsNCg0KaWYoYmluZGV4IDwgMCkgew0KDQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInN1Y2Nl
c3NGbGFnIiwgc3VjY2Vzc0ZsYWcpOw0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJlcnJvciIs
ICJUaGUgPHVzZXJuYW1lPiB0YWcgaXMgbWlzc2luZyBmcm9tIHRoZSBodHRwIHByb2ZpbGUuIik7
DQoNCglyZXR1cm47DQoNCn0NCg0KZWluZGV4ID0gY29ublN0cmluZy5pbmRleE9mKCI8L3VzZXJu
YW1lPiIsIDApOw0KDQppZihlaW5kZXggPCAwKSB7DQoNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRl
cigic3VjY2Vzc0ZsYWciLCBzdWNjZXNzRmxhZyk7DQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIo
ImVycm9yIiwgIlRoZSA8L3VzZXJuYW1lPiB0YWcgaXMgbWlzc2luZyBmcm9tIGJlZ2luaW5nIG9m
IHRoZSBodHRwIHByb2ZpbGUuIik7DQoNCglyZXR1cm47DQoNCn0NCg0KaWRjUGlwZWxpbmUuaW5z
ZXJ0QWZ0ZXIoInVzZXJuYW1lIiwgY29ublN0cmluZy5zdWJzdHJpbmcoYmluZGV4KzEwLGVpbmRl
eCkpOw0KDQoNCmJpbmRleCA9IGNvbm5TdHJpbmcuaW5kZXhPZigiPHBhc3N3b3JkPiIsIDApOw0K
DQppZihiaW5kZXggPCAwKSB7DQoNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigic3VjY2Vzc0Zs
YWciLCBzdWNjZXNzRmxhZyk7DQoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoImVycm9yIiwgIlRo
ZSA8cGFzc3dvcmQ+IHRhZyBpcyBtaXNzaW5nIGZyb20gdGhlIGh0dHAgcHJvZmlsZS4iKTsNCg0K
CXJldHVybjsNCg0KfQ0KDQplaW5kZXggPSBjb25uU3RyaW5nLmluZGV4T2YoIjwvcGFzc3dvcmQ+
IiwgMCk7DQoNCmlmKGVpbmRleCA8IDApIHsNCg0KCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJz
dWNjZXNzRmxhZyIsIHN1Y2Nlc3NGbGFnKTsNCglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZXJy
b3IiLCAiVGhlIDwvcGFzc3dvcmQ+IHRhZyBpcyBtaXNzaW5nIGZyb20gYmVnaW5pbmcgb2YgdGhl
IGh0dHAgcHJvZmlsZS4iKTsNCg0KCXJldHVybjsNCg0KfQ0KDQppZGNQaXBlbGluZS5pbnNlcnRB
ZnRlcigicGFzc3dvcmQiLCBjb25uU3RyaW5nLnN1YnN0cmluZyhiaW5kZXgrMTAsZWluZGV4KSk7
DQoNCg0Kc3VjY2Vzc0ZsYWcgPSAidHJ1ZSI7DQoNCmlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJz
dWNjZXNzRmxhZyIsIHN1Y2Nlc3NGbGFnKTsNCg0KfS8vZW5kIG9mIHRyeSBibG9jaw0KDQpjYXRj
aCAoRXhjZXB0aW9uIGUpIA0Kew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUudG9TdHJp
bmcoKSk7DQp9DQoNCmZpbmFsbHkNCnsNCmlmKGlkY1BpcGVsaW5lICE9IG51bGwgKSANCmlkY1Bp
cGVsaW5lLmRlc3Ryb3koKTsNCn0NCg==</value>
</Values>
