<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">calculateDateDifference</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required startDateTime</value>
    <value>[i] field:0:required endDateTime</value>
    <value>[i] field:0:required startDateFormat</value>
    <value>[i] field:0:required endDateFormat</value>
    <value>[o] field:0:required dateDifferenceSec</value>
    <value>[o] field:0:required dateDifferenceMin</value>
    <value>[o] field:0:required dateDifferenceHr</value>
    <value>[o] field:0:required dateDifferenceDay</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcJc3RhcnREYXRlVGltZSA9ICIiOw0KU3RyaW5nCWVuZERhdGVUaW1lID0g
IiI7DQpTdHJpbmcgc3RhcnREYXRlRm9ybWF0ID0gIiI7DQpTdHJpbmcgZW5kRGF0ZUZvcm1hdCA9
ICIiOw0KaWYgKHBpcGVsaW5lQ3Vyc29yLmZpcnN0KCJzdGFydERhdGVUaW1lIikpDQp7DQoJc3Rh
cnREYXRlVGltZSA9IChTdHJpbmcpIHBpcGVsaW5lQ3Vyc29yLmdldFZhbHVlKCk7DQp9DQppZiAo
cGlwZWxpbmVDdXJzb3IuZmlyc3QoImVuZERhdGVUaW1lIikpDQp7DQoJZW5kRGF0ZVRpbWUgPSAo
U3RyaW5nKSBwaXBlbGluZUN1cnNvci5nZXRWYWx1ZSgpOw0KfQ0KaWYgKHBpcGVsaW5lQ3Vyc29y
LmZpcnN0KCJzdGFydERhdGVGb3JtYXQiKSkNCnsNCglzdGFydERhdGVGb3JtYXQgPSAoU3RyaW5n
KSBwaXBlbGluZUN1cnNvci5nZXRWYWx1ZSgpOw0KfQ0KaWYgKHBpcGVsaW5lQ3Vyc29yLmZpcnN0
KCJlbmREYXRlRm9ybWF0IikpDQp7DQoJZW5kRGF0ZUZvcm1hdCA9IChTdHJpbmcpIHBpcGVsaW5l
Q3Vyc29yLmdldFZhbHVlKCk7DQp9DQoNCmlmIChzdGFydERhdGVUaW1lLmVxdWFscygiIikgfHwg
ZW5kRGF0ZVRpbWUuZXF1YWxzKCIiKSkNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRGF0
ZXMgY2Fubm90IGJlIG51bGwiKTsNCmlmIChzdGFydERhdGVGb3JtYXQuZXF1YWxzKCIiKSB8fCBl
bmREYXRlRm9ybWF0LmVxdWFscygiIikpDQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkRh
dGUgZm9ybWF0cyBjYW5ub3QgYmUgbnVsbCIpOw0KDQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7
DQoNCnRyeSB7DQoJCVNpbXBsZURhdGVGb3JtYXQgc2RmID0gbmV3IFNpbXBsZURhdGVGb3JtYXQo
c3RhcnREYXRlRm9ybWF0KTsNCgkJRGF0ZSBzZHQgPSBzZGYucGFyc2Uoc3RhcnREYXRlVGltZSk7
DQoJCVNpbXBsZURhdGVGb3JtYXQgZWRmID0gbmV3IFNpbXBsZURhdGVGb3JtYXQoZW5kRGF0ZUZv
cm1hdCk7DQoJCURhdGUgZWR0ID0gZWRmLnBhcnNlKGVuZERhdGVUaW1lKTsNCgkJbG9uZyAgdGlt
ZWRpZmYgPSBlZHQuZ2V0VGltZSgpIC0gc2R0LmdldFRpbWUoKTsNCg0KLy8JCVNpbXBsZURhdGVG
b3JtYXQgc3NkZiA9IG5ldyBTaW1wbGVEYXRlRm9ybWF0KCJISDptbTpzcyIpOw0KLy8JCUNhbGVu
ZGFyIGNhbCA9IENhbGVuZGFyLmdldEluc3RhbmNlKCk7DQovLwkJY2FsLmNsZWFyKCk7DQovLwkJ
Y2FsLnNldChDYWxlbmRhci5TRUNPTkQsIChpbnQpIHRpbWVkaWZmIC8xMDAwKTsNCg0KLy8JCURh
dGUgbmV3RGF0ZVRpbWUgPSBjYWwuZ2V0VGltZSgpOw0KLy8JCVN0cmluZyBkaXNwbGF5VGltZT1u
dWxsOw0KDQovLwkJaWYgKGNhbC5nZXQoQ2FsZW5kYXIuREFZX09GX1lFQVIpID4gMSApDQovLwkJ
ICAgIGRpc3BsYXlUaW1lID0gc3NkZi5mb3JtYXQobmV3RGF0ZVRpbWUpICsgIiBhbmQgIiArIChj
YWwuZ2V0KENhbGVuZGFyLkRBWV9PRl9ZRUFSKS0xKSArICIgRGF5KHMpIiA7DQovLwkJZWxzZSAN
Ci8vCQkgICAgZGlzcGxheVRpbWUgPSBzc2RmLmZvcm1hdChuZXdEYXRlVGltZSk7DQoNCgkJU3Ry
aW5nIGRpc3BsYXlUaW1lU2VjID0gTG9uZy50b1N0cmluZyh0aW1lZGlmZi8xMDAwKTsNCgkJU3Ry
aW5nIGRpc3BsYXlUaW1lTWluID0gTG9uZy50b1N0cmluZyh0aW1lZGlmZi82MDAwMCk7DQoJCVN0
cmluZyBkaXNwbGF5VGltZUhyID0gTG9uZy50b1N0cmluZyh0aW1lZGlmZi8zNjAwMDAwKTsNCgkJ
U3RyaW5nIGRpc3BsYXlUaW1lRGF5ID0gTG9uZy50b1N0cmluZyh0aW1lZGlmZi84NjQwMDAwMCk7
DQoNCgkJLy8gcGlwZWxpbmUNCgkJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVs
aW5lLmdldEN1cnNvcigpOw0KCQlwaXBlbGluZUN1cnNvcl8xLmxhc3QoKTsNCgkJcGlwZWxpbmVD
dXJzb3JfMS5pbnNlcnRBZnRlciggImRhdGVEaWZmZXJlbmNlU2VjIiwgZGlzcGxheVRpbWVTZWMp
Ow0KCQlwaXBlbGluZUN1cnNvcl8xLmluc2VydEFmdGVyKCAiZGF0ZURpZmZlcmVuY2VNaW4iLCBk
aXNwbGF5VGltZU1pbik7DQoJCXBpcGVsaW5lQ3Vyc29yXzEuaW5zZXJ0QWZ0ZXIoICJkYXRlRGlm
ZmVyZW5jZUhyIiwgZGlzcGxheVRpbWVIcik7DQoJCXBpcGVsaW5lQ3Vyc29yXzEuaW5zZXJ0QWZ0
ZXIoICJkYXRlRGlmZmVyZW5jZURheSIsIGRpc3BsYXlUaW1lRGF5KTsNCgkJcGlwZWxpbmVDdXJz
b3JfMS5kZXN0cm95KCk7DQoJfSBjYXRjaCAoUGFyc2VFeGNlcHRpb24gZSkgew0KCQl0aHJvdyBu
ZXcgU2VydmljZUV4Y2VwdGlvbigiRXJyb3IgcGFyc2luZyB0aGUgZGF0ZSB0aW1lOiAiICsgZSk7
DQoJfQ0K</value>
</Values>
