<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">callCommanndLine</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required command</value>
    <value>[o] field:0:required bufferLine</value>
    <value>[o] field:0:required successFlag</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9kZWZpbmUgaW5wdXQgdmFyaWFibGVzDQpJRGF0YUN1cnNvciBpZGMgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNClN0cmluZyBjb21tYW5kID0gSURhdGFVdGlsLmdldFN0cmluZyhpZGMgLCAiY29t
bWFuZCIpOw0KDQovL091dHB1dCBWYXJpYWJsZXMNClN0cmluZyBzdWNjZXNzRmxhZyA9ICIiOw0K
U3RyaW5nIGxpbmUgPSBudWxsOw0KU3RyaW5nIGJ1ZmZlckxpbmUgPSAiICI7DQovL0V4ZWN1dGUg
dGhlIGNvbW1hbmQuIEhhbmRsZSB0aGUgZXhjZXB0aW9uIGlmIGl0IGZhaWxzLg0KdHJ5CXsNCglS
dW50aW1lIHN5c3RlbVNoZWxsID0gUnVudGltZS5nZXRSdW50aW1lKCk7DQoJLy9Qcm9jZXNzIG91
dHB1dCA9IHN5c3RlbVNoZWxsLmV4ZWMoInppcCAtMSBDOlxcbmFzXFxKYXZhXFxBcmNoaXZlLnpp
cCBDOlxcbmFzXFxKYXZhXFwqLioiKTsNCglQcm9jZXNzIG91dHB1dCA9IHN5c3RlbVNoZWxsLmV4
ZWMoY29tbWFuZCk7DQoNCglCdWZmZXJlZFJlYWRlciBiciA9IG5ldyBCdWZmZXJlZFJlYWRlciAo
bmV3IElucHV0U3RyZWFtUmVhZGVyKG91dHB1dC5nZXRJbnB1dFN0cmVhbSgpKSk7DQoJd2hpbGUo
KGxpbmUgPSBici5yZWFkTGluZSgpKSAhPSBudWxsICkgeyAJDQoJCWJ1ZmZlckxpbmUgPSBidWZm
ZXJMaW5lICsgbGluZSArICdcbicgOw0KCX0gICAgICAgIC8vIGRpc3BsYXkgcHJvY2VzcyBvdXRw
dXQNCgkNCglpbnQgZXhpdFZhbCA9IG91dHB1dC53YWl0Rm9yKCk7IC8vIGdldCBwcm9jZXNzIGV4
aXQgdmFsdWUNCglidWZmZXJMaW5lID0gYnVmZmVyTGluZSArICAiRXhpdCBWYWx1ZSBpcyA6ICIg
KyBleGl0VmFsOwkNCglzdWNjZXNzRmxhZyA9ICJUcnVlIiA7DQoJaWRjLmluc2VydEFmdGVyKCJi
dWZmZXJMaW5lIiwgYnVmZmVyTGluZSk7DQoJDQoJLy9pZGMuY2xvc2UoKTsNCn0NCmNhdGNoIChF
eGNlcHRpb24gZXgpCXsNCglzdWNjZXNzRmxhZz0iRmFsc2UiOw0KCWJ1ZmZlckxpbmUgPSBleC5n
ZXRNZXNzYWdlKCk7DQp9DQpmaW5hbGx5IHsNCglpZGMuaW5zZXJ0QWZ0ZXIoImJ1ZmZlckxpbmUi
LGJ1ZmZlckxpbmUpOwkNCglpZGMuaW5zZXJ0QWZ0ZXIoInN1Y2Nlc3NGbGFnIiwgc3VjY2Vzc0Zs
YWcpOw0KCQ0KCS8vQWx3YXlzIGRlc3Ryb3kgY3Vyc29ycyB0aGF0IHlvdSBjcmVhdGVkDQoJaWRj
LmRlc3Ryb3koKTsNCn0NCi8vaW5zZXJ0IHRoZSBzdWNjZXNzRmxhZyBpbnRvIHRoZSBwaXBlbGlu
ZQ0K</value>
</Values>
